// Auto-generated from real cricket player data
// Each country maps to arrays of first and last names for mix-and-match generation

const COUNTRY_NAMES = {
  "Afghanistan": {
    first: ["Afsar", "Aftab", "Asghar", "Azmatullah", "Darwish", "Dawlat", "Fareed", "Fazal", "Gulbodin", "Hamid", "Hamza", "Hashmatullah", "Hazratullah", "Ibrahim", "Ihsanullah", "Izatullah", "Javed", "Karim", "Mirwais", "Mohammad", "Mohibullah", "Mujeeb", "Najeeb", "Najibullah", "Nangeyalia", "Naveen-ul-Haq", "Nawroz", "Nijat", "Noor", "Qais", "Raees", "Rahmanullah", "Rahmat", "Rashid", "Rokhan", "Samiullah", "Sayed", "Sediqullah", "Shabir", "Shafiqullah", "Shapoor", "Sharafuddin", "Usman", "Wafadar", "Yamin", "Zahir", "Zamir", "Ziaur", "Zubaid"],
    last: ["Ahmad", "Ahmadi", "Ahmadzai", "Akbari", "Alam", "Ali Zadran", "Ashraf", "Atal", "Barakzai", "Dawlatzai", "Ghani", "Gurbaz", "Haque", "Hassan", "Hotak", "Ishaq", "Janat", "Khan", "kharote", "Mangal", "Masood", "Nabi", "Naib", "Nasim Baras", "Niazai", "Noori", "Omarzai", "Oryakhel", "Rahman", "Rasooli", "Sadiq", "Saleem", "Shah", "Shahidi", "Shahzad", "Shenwari", "Shirzad", "Stanikzai", "Tarakai", "Zadran", "Zazai"]
  },
  "Argentina": {
    first: ["Agustin", "Alan", "Alejandro", "Augusto", "Bruno", "David", "Esteban", "Franz", "Hernan", "Jonathan", "Lautaro", "Martin", "Pedro", "Ramiro", "Ruann", "Santiago", "Steven", "Tomas"],
    last: ["Angeltti", "Arrighi", "Baron", "Bruno", "Bur", "Duggan", "Escobar", "Fennell", "Ferguson", "Hurley", "Husain", "Iturbe", "Kirschbaum", "Kruger", "Mauro", "Musiani", "Mustafa", "Nino", "Rivero", "Rossi", "Siri", "Van Der Merwe"]
  },
  "Australia": {
    first: ["Aaron", "Adam", "Alex", "Andrew", "Ashley", "Ashton", "Ben", "Billy", "Brad", "Brett", "Callum", "Cameron", "Chris", "Clint", "Cooper", "D'Arcy", "Damien", "Daniel", "David", "Dirk", "Doug", "Fawad", "George", "Glenn", "Jack", "Jake", "James", "Jason", "Jhye", "John", "Josh", "Kane", "Luke", "Marcus", "Marnus", "Matthew", "Michael", "Mick", "Mitch", "Mitchell", "Moises", "Nathan", "Nic", "Patrick", "Peter", "Phillip", "Ricky", "Riley", "Ryan", "Scott", "Sean", "Shane", "Shaun", "Simon", "Spencer", "Steve", "Steven", "Stuart", "Tanveer", "Tim", "Travis", "Usman", "Xavier"],
    last: ["Abbott", "Agar", "Ahmed", "Bailey", "Bancroft", "Bartlett", "Behrendorff", "Birt", "Boland", "Bollinger", "Boyce", "Bracken", "Carey", "Christian", "Clark", "Clarke", "Connolly", "Coulter-Nile", "Cummins", "Cutting", "David", "Doherty", "Dunk", "Dwarshuis", "Ellis", "Faulkner", "Ferguson", "Finch", "Fraser-McGurk", "Geeves", "Gilchrist", "Gillespie", "Green", "Haddin", "Handscomb", "Hardie", "Harris", "Harwood", "Hastings", "Hauritz", "Hayden", "Hazlewood", "Head", "Henriques", "Hilfenhaus", "Hodge", "Hogg", "Hopes", "Hughes*", "Hussey", "Inglis", "Johnson", "Kasprowicz", "Katich", "Khawaja", "Klinger", "Labuschagne", "Laughlin", "Lee", "Lewis", "Lynn", "Lyon", "Maddinson", "Marsh", "Martyn", "Maxwell", "McDermott", "McGrath", "McKay", "Meredith", "Muirhead", "Nannes", "Nevill", "Noffke", "North", "O'Keefe", "Paine", "Pattinson", "Philippe", "Pomersbach", "Ponting", "Reardon", "Richardson", "Rohrer", "Ronchi", "Sams", "Sangha", "Short", "Siddle", "Smith", "Stanlake", "Starc", "Stoinis", "Swepson", "Symonds", "Tait", "Turner", "Tye", "Voges", "Wade", "Warner", "Watson", "White", "Wildermuth", "Zampa"]
  },
  "Austria": {
    first: ["Alexander", "Andreas", "Bernhard", "Christian", "Christoph", "Daniel", "David", "Dominik", "Erich", "Fabian", "Felix", "Florian", "Georg", "Hans", "Jakob", "Johann", "Johannes", "Karl", "Klaus", "Lukas", "Manuel", "Markus", "Martin", "Matthias", "Max", "Michael", "Moritz", "Oliver", "Patrick", "Paul", "Peter", "Philipp", "Sebastian", "Simon", "Stefan", "Thomas", "Tobias", "Wolfgang"],
    last: ["Auer", "Bauer", "Baumgartner", "Berger", "Brunner", "Eder", "Egger", "Fischer", "Fuchs", "Gruber", "Haas", "Hofer", "Huber", "Koller", "Lang", "Lehner", "Leitner", "Maier", "Mayer", "Mayr", "Moser", "Muller", "Pichler", "Reiter", "Schmid", "Schmidt", "Schneider", "Schwarz", "Steiner", "Wagner", "Weber", "Wimmer", "Winkler", "Wolf"]
  },
  "Bahamas": {
    first: ["Andrew", "Antonio", "Bhumeshswar", "Dannavan", "Dwight", "Everette", "Festus", "Garcha", "Garfield", "Gregory", "Jagnauth", "Jonathan", "Julio", "Junior", "Keith", "Kervon", "Lee", "Llewellyn", "Marc", "Mario", "Marlon", "Narendra", "Oneil", "Orlando", "Renford", "Roderick", "Rudolph", "Ryan", "Sandeep", "Turan", "Venris", "Whitcliff"],
    last: ["Armstrong", "Atkinson", "Barry", "Benn", "Bennett", "Blair", "Brown", "Burrows", "Davson", "Ekanayake", "Ford", "Fox", "Goud", "Graham", "Harris", "Haven", "Hinds", "Irvin", "Jagroo", "Jemison", "Levy", "Melville", "Mitchell", "Morrison", "Scott", "Stewart", "Tappin", "Taylor", "Weakley", "Wheatley"]
  },
  "Bahrain": {
    first: ["Abdul", "Adil", "Ahmer", "Ali", "Ammad", "Anasim", "Asif", "Babar", "Bilal", "Danish", "David", "Fiaz", "George", "Haider", "Imran", "Janaka", "Junaid", "Mohamed", "Mohammed", "Mohsin", "Muhammad", "Muhammed", "Naveen", "Numan", "Prashant", "Qasim", "Rizwan", "Sachin", "Sai", "Sarfaraz", "Sathaiya", "Shahbaz", "Shahid", "Sikder", "Sohail", "Tahir", "Umer", "Waseeq", "Yasser", "Yousif", "Zeeshan"],
    last: ["Abbas", "Ahmed", "Ali", "Anwar", "Axtell", "Aziz", "Badar", "Basil", "Billah", "Bin Nisar", "Butt", "Chaturanga", "Dar", "Dawood", "Hanif", "Imtiaz", "Iqbal", "Jasnaik", "Khan", "Kumar", "Kurup", "Mahmood", "Majid", "Mansoor", "Mathias", "Nazir", "Rafique", "Safdar", "Salman", "Sameer", "Sarthak", "Thailappan", "Uddin", "Veerapathiran", "Wali", "Younis", "Yousuf", "Zaki", "Zia"]
  },
  "Bangladesh": {
    first: ["Abdur", "Abu", "Abul", "Afif", "Aftab", "Al-Amin", "Alok", "Aminul", "Anamul", "Arafat", "Ariful", "Dhiman", "Ebadat", "Elias", "Farhad", "Hasan", "Imrul", "Jahurul", "Jaker", "Jubair", "Junaid", "Litton", "Mahedi", "Mahmudullah", "Mashrafe", "Mehidy", "Mehrab", "Mithun", "Mohammad", "Mominul", "Mosaddek", "Mukhtar", "Munim", "Mushfiqur", "Mustafizur", "Nadif", "Naeem", "Najmul", "Nasir", "Nasum", "Nazimuddin", "Nazmul", "Nazmus", "Nurul", "Parvez", "Raqibul", "Rishad", "Robiul", "Rony", "Rubel", "Sabbir", "Saif", "Sajidul", "Saqlain", "Shafiul", "Shahadat", "Shahidul", "Shahriar", "Shakib", "Shamim", "Shamsur", "Shoriful", "Shuvagata", "Sohag", "Soumya", "Suhrawadi", "Syed", "Taijul", "Tamim", "Tanvir", "Tanzid", "Tanzim", "Taskin", "Towhid", "Yasir", "Zakir", "Ziaur"],
    last: ["Ahmed", "Al Hasan", "Ali", "Ashraful", "Chowdhury", "Das", "Gazi", "Ghosh", "Haque", "Hasan", "Hasan Sakib", "Hassan", "Hider", "Hom", "Hossain", "Hossain Emon", "Hossain jnr", "Hossain Shanto", "Hridoy", "Iqbal", "Islam", "Jayed", "Kapali", "Kayes", "Mahmud", "Mortaza", "Nafees", "Naim", "Rafique", "Rahim", "Rahman", "Rasel", "Razzak", "Reza", "Sadat", "Saifuddin", "Sajib", "Sarkar", "Shahid", "Shahriar", "Shuvo", "Siddique", "Sunny", "Talukdar"]
  },
  "Belgium": {
    first: ["Antoine", "Bart", "Christophe", "David", "Dries", "Florian", "Gilles", "Guillaume", "Jan", "Jef", "Jonas", "Julien", "Kevin", "Koen", "Laurent", "Louis", "Luc", "Marc", "Mathieu", "Maxime", "Nicolas", "Philippe", "Pieter", "Ruben", "Sander", "Sebastien", "Simon", "Steven", "Thomas", "Tim", "Wim", "Yannick"],
    last: ["Claes", "De Backer", "De Smedt", "Dubois", "Dumont", "Gerard", "Goossens", "Hendrickx", "Hermans", "Jacobs", "Janssens", "Lambert", "Leclercq", "Lemaire", "Leroy", "Maes", "Martin", "Mertens", "Peeters", "Renard", "Simon", "Stevens", "Van Damme", "Vandenberghe", "Willems", "Wouters"]
  },
  "Belize": {
    first: ["Aaron", "Andrew", "Bernan", "Cornel", "Ean", "Gareth", "Garret", "George", "Glenford", "Glenroy", "Herbert", "Keagan", "Keenan", "Kenroy", "Kenton", "Maurice", "Muhammad", "Nathan", "T'shaka", "Travis", "Winford"],
    last: ["Banner", "Broaster", "Brown", "Castillo", "Flowers", "Hyde", "Joseph", "Muslar", "Patterson", "Reynold", "Reynolds", "Samuels", "Stephenson", "Tillett", "Young", "Zaghlool"]
  },
  "Bermuda": {
    first: ["Alex", "Allan", "Cejay", "Chare", "Charles", "Chris", "Christian", "Curt", "David", "Dean", "Delray", "Delyone", "Derrick", "Deunte", "Dominic", "Dwayne", "Fiqre", "Garvin", "George", "Hasan", "Irving", "Jabari", "Jacob", "Jacobi", "James", "Janeiro", "Jarryd", "Jason", "Jekon", "Jonte", "Joshua", "Justin", "Kamal", "Kamau", "Kwame", "Kyle", "Lionel", "Macai", "Macquille", "Malachi", "Okera", "Oliver", "Onias", "Oronde", "Ricardo", "Rodney", "Ryan", "Saleem", "Sam", "Sinclair", "Stefan", "Steven", "Tamauri", "Terryn", "Traddie", "Tre", "Zeko"],
    last: ["Albertze", "Anderson", "Aparicio", "Bascome", "Bashir", "Borden", "Brangman", "Burgess", "Cann", "Celestine", "Crockwell", "Darrell", "Dore", "Douglas", "Durham", "Edness", "Foggo", "Fray", "Gilbert", "Hemp", "Hodsoll", "Jones", "Kelly", "Leverock", "Manders", "Minors", "Mukuddem", "O'Brien", "Outerbridge", "Pitcher", "Rawlins", "Richardson", "Robinson", "Romaine", "Sabir", "Simmons", "Simpson", "Smith", "Steede", "Stovell", "Trott", "Tucker", "Walker"]
  },
  "Bhutan": {
    first: ["Anand", "Dawa", "Gakul", "Jigme", "Karma", "Kezang", "Kinley", "Kishen", "Kumar", "Manoj", "Namgang", "Namgay", "Ngawang", "Ramesh", "Ranjung", "Rekash", "Sanjeevan", "Sherab", "Sonam", "Suprit", "Tandin", "Tashi", "Tenjin", "Tenzin", "Thinley", "Thukten", "Tobden", "Tshering"],
    last: ["Adhikari", "Chejay", "Chopel", "Chophel", "Dawa", "Dorji", "Ghalley", "Gurung", "Jamtsho", "Jigme Yoezer", "Limbu", "Loday", "Mikyo Dorji", "Mongar", "Nima", "Penjor", "Phuntsho", "Pradhan", "Rabgey", "Singye", "Subba", "Tashi", "Thinley", "Wangchuk", "Wangchuk jnr", "Yeshi"]
  },
  "Botswana": {
    first: ["Adithiya", "Ameer", "Boemo", "Boteng", "Dhruv", "Dimpho", "Hemal", "Inzimam", "James", "Karabo", "Katlo", "Leano", "Losika", "Michael", "Mmoloki", "Monroux", "Nabil", "Phemelo", "Reginald", "Reynier", "Rod", "Sooraj", "Tharindu", "Thatayaone", "Tshepo", "Tumelo", "Valentine", "Vinoo", "Waseem", "William", "Zain"],
    last: ["Abbasi", "Badenhorst", "Balakrishnan", "Kasselman", "Kegasitswe", "Kgosiemang", "Khumalo", "Kollery", "Maisuria", "Makgale", "Maphane", "Maphosa", "Master", "Mbaiwa", "Mbazo", "Modise", "Mooketsi", "Moses", "Motlanka", "Motlhanka", "Mpatane", "Nehonde", "Nkosana", "Perera", "Phaswana", "Piet", "Pragji", "Rangaswamy", "Saiyed", "Silas", "Swart", "Tajbhay", "Tshose"]
  },
  "Brazil": {
    first: ["Fahad", "Greigor", "Ismat", "Jaimin", "John", "Kamal", "Kevin", "Luis", "Luiz", "Muhammad", "Richard", "Victor", "Yasar"],
    last: ["Ali", "Allen", "Avery", "Bishnoi", "Caisley", "Goncalves", "Haroon", "Poubel", "Rodrigues", "Saleem", "Silva", "Singleton", "Ullah"]
  },
  "Bulgaria": {
    first: ["Agagyul", "Ahsan", "Akshay", "Andrey", "Aravinda", "Asad", "Aswad", "Bakhtiar", "Boiko", "Danyal", "Delrick", "Dimo", "Fayaz", "Gagandeep", "Hristo", "Huzaif", "Isa", "Ivaylo", "Jacob", "Karthik", "Kevin", "Kiran", "Mukul", "Nikolay", "Omar", "Prakash", "Rohan", "Rohit", "Saim", "Sandeep", "Subinthan", "Sulaiman", "Tarun", "Valter", "Vasil", "Zaid", "Zain", "Zeerak"],
    last: ["Ahmadhel", "Albin", "Ali", "Ali Rehemtulla", "Asif", "Bhavesh Patel", "Chughtai", "D'Souza", "Dasan", "De Silva", "Dhiman", "Dikov", "Harikumar", "Hristov", "Hussain", "Ivanov", "Kadyan", "Katzarski", "Khan", "Lakov", "Lilov", "Mishra", "Mohammad", "Nair", "Nankov", "Nikolov", "Pillai", "Raja", "Rassol", "Singh", "Soosiyakumar", "Soulat", "Tahiri", "Varghese", "Yadav", "Yordanov", "Yousuf", "Zaroo"]
  },
  "Cambodia": {
    first: ["Bora", "Chan", "Chann", "Chanthol", "Chea", "Chhun", "Dara", "Heng", "Kakada", "Keo", "Kosal", "Ly", "Mao", "Narith", "Nhem", "Phalla", "Phearom", "Pheakdey", "Piseth", "Ponleu", "Rith", "Rithya", "Sarath", "Serey", "Seth", "Sinat", "Sokha", "Sophal", "Sopheak", "Thearith", "Vannak", "Vibol", "Vicheka", "Vuth", "Yean"],
    last: ["Bun", "Chan", "Chhay", "Chhim", "Chhorn", "Chhuon", "Eng", "Hak", "Hean", "Hem", "Heng", "Hor", "Im", "Keo", "Khem", "Khim", "Kim", "Kong", "Lim", "Long", "Ly", "Mean", "Meas", "Nath", "Nhean", "Nhem", "Ouk", "Pen", "Phan", "Pheng", "Prak", "Sam", "Sar", "Seng", "Soeun", "Som", "Sun", "Suon", "Taing", "Tan", "Tep", "Thong", "Touch", "Ung", "Vann", "Yim"]
  },
  "Cameroon": {
    first: ["Abdoulaye", "Alain", "Alexis", "Appolinaire", "Bruno", "Charles", "Dipita", "Faustin", "Idriss", "Julien", "Kulbhushan", "Maxwell", "Narcisse", "Protais", "Roger", "Roland"],
    last: ["Abanda", "Abega", "Amah", "Aminou", "Atangana", "Balla", "Fru", "Jadhav", "Loic", "Mengoumou", "Mpegna", "Ndouteng", "Ondoa", "Tchakou", "Toube"]
  },
  "Canada": {
    first: ["Aaron", "Abdool", "Abraash", "Abzal", "Akhil", "Ammar", "Armaan", "Arsalan", "Ashif", "Ashish", "Balaji", "Cecil", "Damodar", "Dillon", "Dilpreet", "Eion", "Geoff", "Hamza", "Harsh", "Harvir", "Henry", "Hiral", "Ian", "Jatinderpal", "Jeremy", "Jimmy", "John", "Junaid", "Kaleem", "Kanwarpal", "Karun", "Kenneth", "Khurram", "Khushroo", "Manny", "Mark", "Matthew", "Mohammad", "Navneet", "Nicholas", "Nikhil", "Nitish", "Pargat", "Parth", "Parveen", "Ramesh", "Ravinderpal", "Rayyan", "Raza-ur-Rehman", "Rishiv", "Rizwan", "Rodrigo", "Romesh", "Rustam", "Ruvindu", "Saad", "Salman", "Sandeep", "Sanjayan", "Satsimranjit", "Shaheed", "Shahid", "Shreyas", "Srimantha", "Steven", "Sunil", "Trevin", "Tyson", "Uday", "Umar", "Usman", "Zahid", "Zubin"],
    last: ["Ahmadzai", "Aulakh", "Bagai", "Baidwan", "Bajwa", "Barnett", "Bastiampillai", "Bhagwan", "Bhatti", "Billcliff", "Bin Zafar", "Cheema", "Chohan", "Daesrath", "David", "Davison", "Dean", "Desai", "Dhaliwal", "Dhaniram", "Dhindsa", "Dutta", "Eranga", "Gordon", "Gunasekera", "Hansra", "Heyliger", "Hussain", "Iqbal", "Jethi", "Johnson", "Joshi", "Jyoti", "Kamyuka", "Kapoor", "Katchay", "Keshvani", "Khalid", "Khan", "Kirton", "Kumar", "Limbada", "Matharu", "Montfort", "Movva", "Mulla", "Nazar", "Osinde", "Patel", "Pathan", "Pervez", "Qadir", "Qazi", "Rao", "Samad", "Sana", "Siddiqui", "Singh", "Spoors", "Surkari", "Tariq", "Tathgur", "Thaker", "Thomas", "Thuraisingam", "Wadia", "Welsh", "Wijeyeratne"]
  },
  "Cayman Islands": {
    first: ["Adrian", "Ainsley", "Akhilesh", "Akshay", "Alessandro", "Alistair", "Brian", "Chad", "Conroy", "Darren", "Demar", "Franklyn", "Gregory", "Jahmeal", "Jalon", "Keneil", "Kenute", "Kervin", "Kevin", "Kevon", "Luke", "Marvin", "Michael", "Mohan", "Omar", "Patrick", "Paul", "Pearson", "Ramon", "Romeo", "Ryan", "Sacha", "Saheed", "Steve", "Thilina", "Troy", "Zachary"],
    last: ["Bazil", "Best", "Bovell", "Buchanan", "Cato", "Chin", "Corbin", "De Alwis", "Dunka", "Ebanks", "Gavde", "Gordon", "Hall", "Harrington-Myers", "Hauptfleisch", "Heron", "Hewa", "Hinds", "Ifill", "Irving", "Johnson", "Linton", "Manivannan", "Manning", "McLaughlin", "Mohamed", "Morris", "Naidoo", "Sealy", "Smith", "Strydom", "Swack", "Taylor", "Tulloch", "Wight", "Willis", "Wright"]
  },
  "Chile": {
    first: ["Alex", "Amit", "Aresh", "Chris", "Hardev", "Hirenkumar", "Ignacio", "Irfan", "Kamlesh", "Major", "Mayanak", "Michael", "Rolando", "Shoaib"],
    last: ["Carthew", "Emmott", "Gazi Hossain", "Gupta", "Lisboa", "Mandy", "Meade", "Mir", "Patel", "Rivas", "Singh", "Srivastav", "Uniyal"]
  },
  "China": {
    first: ["Chen", "Deng", "Dengzhi", "Haotian", "Hong", "Huang", "Jing", "Luo", "Ma", "Ning", "Qingshan", "Shenjian", "Shi", "Tian", "Wang", "Wei", "Xie", "Yin", "Yun", "Yunfeng", "Zhao", "Zhuang", "Zong", "Zou"],
    last: ["Chenhao", "Guo Lei", "Hui Cai", "Jiang Yan", "Jinfeng", "Jinqi", "Junjie", "Kui", "Kunkun", "Li", "Liuyang", "Ma", "Qi", "Qiancheng", "Sen Qun", "Shilin", "Sun", "Tan", "Tianle", "Xiaoran", "Ya", "Yu Feng", "Yuechao", "Zelin", "Zhang", "Zheng", "Zhu", "Zhuo Yue"]
  },
  "Cook Islands": {
    first: ["Aue", "Ben", "Cory", "Dan", "Davis", "Gabe", "Glenn", "Hayden", "Liam", "Ma'ara", "Thomas", "Tomakanute", "Tomasi", "William"],
    last: ["Ave", "Denny", "Dickson", "Kokaua", "Miller", "Parima", "Raymond", "Ritawa", "Simpson", "Teinaki", "Vakatini", "Vanuarua"]
  },
  "Costa Rica": {
    first: ["Christopher", "Daniel", "Esteban", "Gopinath", "Joel", "Mattew", "Nanda", "Oscar", "Oswald", "Prajwel", "Sachin", "Sham", "Sudesh", "Zain"],
    last: ["Cutinho", "Fournier", "George", "Kumar", "Mejia", "Murali", "Murari", "Pillai", "Prasad", "Ravikumar", "Sam Arthur", "Soto", "Thomas", "ul Tashnam"]
  },
  "Croatia": {
    first: ["Akshay", "Alen", "Aman", "Antonio", "Arpit", "Arun", "Boro", "Christopher", "Daniel", "Dominik", "Hariprasad", "Hrvoje", "Jason", "Jawahar", "Jeffrey", "John", "Kresimir", "Luka", "Mate", "Naseem", "Nikola", "Pero", "Rashid", "Saghar", "Sam", "Sheldon", "Sohail", "Vasu", "Vedran", "Vigneshwaran", "Wasal"],
    last: ["Ahmad", "Bitis", "Bosnjak", "Chaubey", "Danikula", "Davidovic", "Daxini", "Faletar", "Grzinic", "Hajnic", "Hashmi", "Houghton", "Jerkovic", "Jukic", "Kekez", "Khan", "Magdalenic", "Maheshwari", "Manzoor", "Marsic", "Newton", "Pulibanti", "Rathinasamy", "Satheedevi", "Sathyan", "Shukla", "Stubbs", "Turkich", "Valjalo", "Vujnovich", "Zanko"]
  },
  "Cyprus": {
    first: ["Abdul", "Akila", "Azan", "Balbir", "BLCS", "Chamal", "Chamila", "Gurpratap", "Harvinder", "Iftekar", "Mangala", "Michalis", "Mohsin", "Muhammad", "Murtaza", "Nalin", "Neeraj", "Qasim", "Rafiqul", "Rajwinder", "Riyaz", "Roman", "Ruwan", "Sachithra", "Scott", "Shoaib", "Syed", "Tejwinder", "Waqar", "Yasir", "Zeeshan"],
    last: ["Ahmed", "Ali", "Anwar", "Arachchilage", "Austin", "Baig", "Brar", "Farooq", "Gamage", "Hussain", "Islam", "Jaman", "Kajalwala", "Kalugala", "Ketiyage", "Kumara", "Kyriacou", "Manan", "Mazumder", "Mehmood", "Pathirana", "Raza", "Sadun", "Sarwar", "Singh", "Tiwari", "Wellage", "Yamin"]
  },
  "Czech Republic": {
    first: ["Abul", "Ali", "Arshad", "Arun", "Brigham", "Divyendra", "Dylan", "Edward", "Hilal", "Honey", "Jan", "Kayul", "Kranthi", "Kushalkumar", "Kyle", "Mikulas", "Naveed", "Neeraj", "Paaras", "Paul", "Rahat", "Riaz", "Ritik", "Sabawoon", "Sahil", "Sameera", "Satyajit", "Sazib", "Sharan", "Shaun", "Shoumyadeep", "Shripal", "Shubhranshu", "Siddarth", "Smit", "Sonny", "Sudesh", "Sudhir", "Sudita", "Sumit", "Surya", "Tripurari", "Ushan", "Venkatesh", "Vojtech", "Vyshakh"],
    last: ["Afridi", "Ahmad", "Ahmed", "Ali", "Ashokan", "Bhuiyan", "Chaudhary", "Clephane", "Dalton", "Davizi", "Farhad", "Gajjar", "Gilham", "Gladston", "Gori", "Goud", "Grover", "Hasa", "Hayat", "Hoffman", "Jagannivasan", "Khari", "Knowles", "Lal", "Marghashayam", "Mehta", "Mendon", "Patel", "Pokhriyal", "Rakshit", "Ramakrishnan", "Rengarajan", "Sengupta", "Singh", "Smith", "Stary", "Steyn", "Taylor", "Thenannahelage", "Tomar", "Tyagi", "Udugalage", "Venkataswamy", "Waqar", "Waththage", "Wickramasekara"]
  },
  "Denmark": {
    first: ["Alexander", "Anders", "Bo", "Christoffer", "Christian", "Emil", "Erik", "Frederik", "Hans", "Henrik", "Jakob", "Jesper", "Jonas", "Kasper", "Kristian", "Lars", "Mads", "Magnus", "Martin", "Mathias", "Mikkel", "Morten", "Nicolai", "Niels", "Oliver", "Peter", "Rasmus", "Sebastian", "Simon", "Soren", "Thomas", "Tobias", "Viktor", "William"],
    last: ["Andersen", "Bech", "Christensen", "Dahl", "Frederiksen", "Hansen", "Henriksen", "Holm", "Jakobsen", "Jensen", "Johansen", "Jorgensen", "Knudsen", "Kristensen", "Larsen", "Lund", "Madsen", "Moller", "Mortensen", "Nielsen", "Nygaard", "Olsen", "Pedersen", "Petersen", "Poulsen", "Rasmussen", "Sorensen", "Thomsen", "Vestergaard"]
  },
  "England": {
    first: ["Adil", "Ajmal", "Alastair", "Alex", "Amjad", "Andrew", "Ben", "Boyd", "Brydon", "Chris", "Craig", "Dan", "Danny", "Darren", "David", "Dawid", "Dimitri", "Ed", "Eoin", "Gareth", "George", "Geraint", "Graeme", "Gus", "Harry", "Ian", "Jacob", "Jade", "Jake", "James", "Jamie", "Jason", "Jeremy", "Joe", "Jofra", "John", "Jon", "Jonathan", "Jonny", "Jordan", "Jos", "Kevin", "Lewis", "Liam", "Luke", "Marcus", "Mark", "Mason", "Matt", "Michael", "Moeen", "Monty", "Oli", "Owais", "Patrick", "Paul", "Phil", "Ravi", "Reece", "Rehan", "Richard", "Robert", "Ryan", "Sajid", "Sam", "Samit", "Saqib", "Scott", "Stephen", "Steve", "Steven", "Stuart", "Tim", "Tom", "Tymal", "Vikram", "Will"],
    last: ["Ahmed", "Ali", "Ambrose", "Anderson", "Archer", "Atkinson", "Bairstow", "Ball", "Banton", "Batty", "Bell", "Bethell", "Billings", "Bopara", "Borthwick", "Bresnan", "Briggs", "Broad", "Brook", "Brown", "Buttler", "Carberry", "Carse", "Collingwood", "Cook", "Cox", "Crane", "Curran", "Dalrymple", "Davies", "Dawson", "Denly", "Dernbach", "Duckett", "Finn", "Flintoff", "Foakes", "Foster", "Garton", "Gleeson", "Gough", "Gregory", "Gurney", "Hales", "Harmison", "Jacks", "Jones", "Jordan", "Joyce", "Key", "Khan", "Kieswetter", "Kirtley", "Lewis", "Livingstone", "Lumb", "Maddy", "Mahmood", "Malan", "Mascarenhas", "Meaker", "Mills", "Morgan", "Mousley", "Mustard", "Nixon", "Overton", "Panesar", "Parkinson", "Parry", "Patel", "Pietersen", "Plunkett", "Prior", "Rankin", "Rashid", "Read", "Root", "Roy", "Salt", "Schofield", "Shah", "Shahzad", "Sidebottom", "Smith", "Snape", "Solanki", "Stokes", "Stone", "Strauss", "Swann", "Topley", "Tredwell", "Tremlett", "Trescothick", "Trott", "Turner", "Vaughan", "Vince", "Willey", "Woakes", "Wood", "Wright", "Yardy"]
  },
  "Estonia": {
    first: ["Aditya", "Ali", "Arslan", "Ashish", "Ashraful", "Ayush", "Ben", "Bilal", "Dave", "Elias", "Habib", "Kalle", "Maidul", "Malcolm", "Marko", "MD", "Moshiur", "Murali", "Pranay", "Ram", "Ramesh", "Sahil", "Saqib", "Stuart", "Tim", "Timothy", "Vimal"],
    last: ["Amjad", "Chauhan", "Cross", "Dwivedi", "Filer", "Gheewala", "Hasan", "Hook", "Islam", "Jones", "Khan", "Krishan", "Masood", "Masud", "Naveed", "Obili", "Panwar", "Paul", "Rahman", "Rana", "Raza", "Robson", "Sedgwick", "Shoyaib", "Shuvo", "Tanna", "Ummat", "Vaik", "Vislapuu"]
  },
  "Fiji": {
    first: ["Delaimatuku", "Jikoi", "Jikoibure", "Jone", "Josaia", "Kitiano", "Maciu", "Metuisela", "Noa", "Peni", "Petero", "Riyad", "Saimoni", "Samuela", "Sekove", "Seru", "Sosiceni", "Tevita", "Tukana", "Viliame"],
    last: ["Acawei", "Baleicikobia", "Batinibulu", "Beitaki", "Cabebula", "Delai", "Draunivudi", "Gauna", "Khan", "Kida", "Maraiwai", "Ravoka", "Tavo", "Tuitoga", "Tupou", "Valenikuila", "Veikauyaki", "Vuniwaqa", "Waqavakatoga", "Weleilakeba", "Yabaki"]
  },
  "Finland": {
    first: ["Adnan", "Akhil", "Amjad", "Aniketh", "Aravind", "Areeb", "Atif", "Faheem", "Hariharan", "Jonathan", "Jordan", "Mahesh", "Maneesh", "Matias", "Matthew", "Md", "Mohammad", "Muhammad", "Nathan", "Naveed", "Parveen", "Peter", "Raaz", "Rubal", "Sapan", "Shoaib", "Sumit", "Tatu", "Tonmoy", "Vanraaj", "Waqas"],
    last: ["Arjunan", "Asaduzzaman", "Brasier", "Chauhan", "Collins", "Dandapani", "Gallagher", "Imran", "Jenkinson", "Kumar", "Mehta", "Mohammad", "Mohan", "Nellancheri", "Nurul Huda", "O'Brien", "Padhaal", "Pathak", "Pusthay", "Quadir", "Qureshi", "Raja", "Rasheed", "Saha", "Scamans", "Shahid", "Sher", "Singh", "Syed", "Tambe", "Vehvil\u00c3\u00a4inen", "Ziaur Rehman"]
  },
  "France": {
    first: ["Abdul", "Abdulmalik", "Alestin", "Ammar", "Dawood", "Dayanidhi", "Devankumar", "Gustav", "Hevit", "Ibrahim", "Jean-Luc", "Jubaid", "Lingeswaran", "Mobashar", "Mukhtar", "Mustafa", "Noman", "Paul", "Pirakajan", "Rahmatullah", "Ravichandran", "Riyas", "Rohullah", "Shahzeb", "Shayam", "Subash", "Suventhiran", "Usman", "Virk", "Zain"],
    last: ["Ahamed", "Ahmad", "Ahmadzai", "Alam", "Ali", "Amirdalingame", "Amjad", "Ashraf", "Bazirhak", "Benoit", "Canessane", "Ghulami", "Jabarkhel", "Jackson", "Johnmary", "Khan", "Lambourdiere", "Mangal", "Mckeon", "Mohammed", "Naeem", "Omer", "Parvady", "Pavadaikannan", "Pirabakaran", "Rahman", "Santhirakumaran", "Shahid", "Warnakulasuriya", "Zahir"]
  },
  "Gambia": {
    first: ["Abubacarr", "Andre", "Aniru", "Ansumana", "Basiru", "Fallou", "Frank", "Gabriel", "Ismaila", "Joseph", "Mbye", "Modou", "Muhammed", "Musa", "Mustapha", "Nicolas", "Ousman", "P", "Peter"],
    last: ["Badjan", "Bah", "Bojang", "Camara", "Campbell", "Cherry", "Conteh", "Dumbuya", "Faye", "Jarju", "Jaye", "Jobarteh", "Kuyateh", "Manga", "Riley", "Suwareh", "Tanba", "Thorpe", "Touray"]
  },
  "Germany": {
    first: ["Abdul", "Abdul-Shakoor", "Ahmadschah", "Ahmed", "Amir", "Amith", "Asad", "Azmat", "Craig", "Daniel", "Dieter", "Dylan", "Faisal", "Fayaz", "Ghulam", "Harish", "Harmanjot", "Husnain", "Israr", "Izatullah", "Jagdeep", "Joshua", "Justin", "Matthew", "Michael", "Mudassar", "Muslim", "Nooruddin", "Rishi", "Rohit", "Sachin", "Sahir", "Sajid", "Shahid", "Shoaib", "Sri", "Talha", "Vaseekaran", "Venkatraman", "Vijayshankar", "Walter", "Zahid"],
    last: ["Afridi", "Ahmadi", "Ahmadzai", "Ali", "Aritharan", "Bashir", "Behr", "Bharathi", "Blignaut", "Broad", "Chikkannaiah", "Dawlatzai", "Ganesan", "Kabeer", "Khan", "Klein", "Liaqat", "Mandy", "Mangal", "Meschede", "Mohammad", "Montgomery", "Mubashir", "Muhammad", "Mujadady", "Naqash", "Pillai", "Rahimzei", "Richardson", "Sarma", "Singh", "Srinivasan", "Stanikzai", "van Heerden", "Wardak", "Weston", "Yar", "Zadran"]
  },
  "Ghana": {
    first: ["Alex", "Amoluk", "Aziz", "Daniel", "David", "Devender", "Francis", "Frank", "Gagandeep", "Godfred", "Isaac", "James", "Julius", "Kelvin", "Kofi", "Lakmal", "Mark", "Michael", "Moses", "Nurudeen", "Obed", "Paul", "Peter", "Philip", "Rexford", "Richmond", "Samson", "Simon", "Syed", "Theodore", "Vincent"],
    last: ["Aboagye", "Anafie", "Ananya", "Anefie", "Ankrah", "Aqeel Israr", "Ateak", "Awala", "Awiah", "Ayoleyine", "Baaleri", "Bagabena", "Bakiweyem", "Bakum", "Bawa", "Harvey", "Ibrahim", "Joseph", "Mensah", "Osei", "Pereira", "Perera", "Singh", "Sualley", "Vifah", "Yevugah"]
  },
  "Gibraltar": {
    first: ["Adam", "Alex", "Andrwe", "Balaji", "Bryan", "Charles", "Chris", "Christian", "Dave", "Edmund", "Iain", "Ian", "Jack", "James", "Jonathan", "Joseph", "Julian", "Kabir", "Kayron", "Kenroy", "Kieron", "Louis", "Luke", "Mark", "Matthew", "Nikhil", "Patrick", "Philip", "Richard", "Samarth", "Tim", "Timothy", "Zachary"],
    last: ["Advani", "Bacarese", "Bodha", "Bruce", "Caruana", "Cleasby", "Collado", "Cunningham", "Delany", "Farrell", "Ferrary", "Fitzgerald", "Freyone", "Garratt", "Gouws", "Harrison", "Hatchman", "Horrocks", "Hunter", "J Stagno", "Latin", "Marples", "Mirpuri", "Nestor", "Orfila", "Packard", "Pai", "Pyle", "Raikes", "Reyes", "Robeson", "Rocca", "Sanderson", "Sawyer", "Simpson", "West", "Whelan", "Zammitt"]
  },
  "Greece": {
    first: ["Alexandros", "Ali", "Alkinoos", "Amarpreet", "Anastasios", "Andreas", "Aristides", "Arslan", "Aslam", "Asrar", "Christodoulos", "Georgios", "Gerasimos", "Ilias", "Muhammad", "Nikolaos", "Panagiotis", "Shaffeq", "Spiridon", "Spiros", "Spyridon", "Syed", "Thomas"],
    last: ["Abdulla Popalzae", "Ahmed", "Amanullah", "Anemogiannis", "Aspiotis", "Awais", "Bantzas", "Bardis", "Bogdanos", "Bogdos", "Fatouros", "Galanis", "Gasteratos", "Goustis", "Karvelas", "Lagos", "Magafas", "Manatos", "Manousis", "Mehmi", "Mohammad", "Mourikis", "Muhammad", "Nikitas", "Siriotis", "Zotos"]
  },
  "Guernsey": {
    first: ["Adam", "Anthony", "Ashley", "Ben", "Benjamin", "Charles", "Dane", "David", "Declan", "Harry", "Isaac", "Jason", "Jordan", "Josh", "Lucas", "Luke", "Martin", "Matthew", "Max", "Nic", "Oliver", "Thomas", "Tom", "William"],
    last: ["Barker", "Breban", "Buckle", "Butler", "Dale-Bradley", "Damarell", "Edward Johnson", "Ellis", "Ferbrache", "Fitchet", "Hooper", "Johnson", "Kimber", "Kirk", "Le Tissier", "Martel", "Martin", "Mullen", "Newey", "Nightingale", "Nussbaumer", "Peatfield", "Stokes", "Thomas Bichard", "Veillard", "Vorster", "Wentzel", "Wright"]
  },
  "Hong Kong": {
    first: ["Aarush", "Adil", "Adit", "Aftab", "Ahsan", "Aizaz", "Akbar", "Anas", "Ankur", "Anshy", "Asif", "Ateeq", "Ayush", "Babar", "Christopher", "Courtney", "Daljeet", "Dhananjay", "Ehsan", "Giacomo", "Hamed", "Haroon", "Haseeb", "Hassan", "Irfan", "Jamie", "Jason", "Kinchit", "Kyle", "Li", "Mark", "Martin", "Max", "Mohammad", "Mohsin", "Muhammad", "Munir", "Nadeem", "Najeeb", "Nasrulla", "Niaz", "Nizakat", "Raag", "Rajab", "Roy", "Ryan", "Scott", "Shahid", "Shiv", "Simandeep", "Tanveer", "Tanwir", "Waqas", "Yasim", "Zeeshan"],
    last: ["Abbasi", "Afzal", "Ahmed", "Ali", "Amar", "Amjad", "Arshad", "Atkinson", "Barkat", "Bhagwat", "Campbell", "Carter", "Chapman", "Christie", "Coetzee", "Dar", "Ghazanfar", "Gorawara", "Hayat", "Hussain", "Iqbal", "Kai Ming", "Kapur", "Khan", "Khan Mohammad", "Kruger", "Lamplough", "Lamsam", "Lui", "Mathur", "McKechnie", "Mehmood", "Murtaza", "Nawaz", "Rana", "Rao", "Rath", "Shah", "Sharma", "Shukla", "Singh", "Tucker", "Waheed", "Wasif"]
  },
  "Hungary": {
    first: ["Abbas", "Abhijeet", "Abhishek", "Abhitesh", "Abishek", "Akramullah", "Ali", "Amal", "Asanka", "Bhavani", "Chris", "Gabor", "Harshvardhan", "Kalum", "Khaibar", "Mark", "Matthew", "Muhammad", "Nishanta", "Safi", "Sandeep", "Sanjay", "Satyadeep", "Sheikh", "Tejendra", "Vinoth", "Ximus", "Zeeshan"],
    last: ["Adapaka", "Ahuja", "Ainsworth", "Akurugoda", "Ashwathnarayana", "Deldar", "Dowle", "du Plooy", "Farasat", "Fontaine", "Ghani", "Jacob", "Kheterpal", "Kukikhel", "Kumar", "Liyanaye", "Malikzada", "Mandhyan", "Mohandas", "Prashar", "Raj", "Rasik", "Ravindran", "Saqlain", "Torok", "Usman", "Valivarthi", "Weligamage", "Yalmaz", "Zahir"]
  },
  "India": {
    first: ["Abhishek", "Ajinkya", "Ajit", "Akshar", "Ambati", "Amit", "Arshdeep", "Ashish", "Ashok", "Avesh", "Bhuvneshwar", "Brainder", "Chetan", "Deepak", "Devdutt", "Dhawal", "Dhruv", "Dinesh", "Gautam", "Harbhajan", "Hardik", "Harshal", "Harshit", "Irfan", "Ishan", "Ishant", "Jasprit", "Jaydev", "Jitesh", "Joginder", "Karn", "Kedar", "Khaleel", "Krunal", "Kuldeep", "Lakshmipathy", "Lokesh", "Mandeep", "Manish", "Manoj", "Mayank", "Mohammad", "Mohammed", "Mohit", "MS", "Mukesh", "Munaf", "Murali", "Naman", "Navdeep", "Nitish", "Parthiv", "Parvez", "Parvinder", "Pawan", "Piyush", "Pragyan", "Prasidh", "Praveen", "Prithvi", "Rahul", "Ramandeep", "Ravi", "Ravichandran", "Ravindra", "Rinku", "Rishabh", "Rishi", "Riyan", "Robin", "Rohit", "RP", "Ruturaj", "Sachin", "Sai", "Sandeep", "Sanju", "Shardul", "Shikhar", "Shivam", "Shreyas", "Shubman", "Siddarth", "Sreenath", "Sreesanth", "Stuart", "Subramaniam", "Sudeep", "Suresh", "Suryakumar", "T", "Tilak", "Tushar", "Umesh", "Umran", "Varun", "Venkatesh", "Vijay", "Vinay", "Virat", "Virender", "Washington", "Yashasvi", "Yusuf", "Yuvraj", "Yuzvendra", "Zaheer"],
    last: ["Agarkar", "Ahmed", "Aravind", "Ashwin", "Awana", "Badrinath", "Balaji", "Binny", "Bishnoi", "Bumrah", "Chahal", "Chahar", "Chakravarthy", "Chawla", "Deshpande", "Dhawan", "Dhoni", "Dinda", "Dravid", "Dube", "Gaikwad", "Gambhir", "Gill", "Hooda", "Iyer", "Jadeja", "Jadhav", "Jaiswal", "Jurel", "Karthik", "Kartik", "Kaul", "Khan", "Kishan", "Kohli", "Krishna", "Kulkarni", "Kumar", "Kumar Reddy", "Malik", "Markande", "Mavi", "Mishra", "Mongia", "Natarajan", "Negi", "Nehra", "Ojha", "Padikkal", "Pandey", "Pandya", "Pant", "Parag", "Patel", "Pathan", "Rahane", "Rahul", "Raina", "Rana", "Rasool", "Rayudu", "Saini", "Sakariya", "Samson", "Sehwag", "Shami", "Shankar", "Sharma", "Shaw", "Singh", "Siraj", "Sran", "Sudharsan", "Sundar", "Tendulkar", "Thakur", "Tiwary", "Tripathi", "Tyagi", "Unadkat", "Uthappa", "Varma", "Vijay", "Warrier", "Yadav"]
  },
  "Indonesia": {
    first: ["Ahmad", "Andreas", "Anjar", "Apriliandi", "Arya", "Danilson", "Desandri", "Dewa", "Dhanesh", "Febrianto", "Ferdinando", "Gaurav", "Gede", "Julang", "Kadek", "Ketut", "Kirubasankar", "Maxi", "Muhaddis", "Muhammad", "Padmakar", "Putra", "Rizky", "Sakthi", "Wayan"],
    last: ["Afis", "Arta", "Artawan", "Banunaek", "Budiarta", "Darmawan", "Dharma Kesuma", "Dzulfikar", "Gamantika", "Hawoe", "Heo", "Kisawa", "Koda", "Muhaddis", "Mushtaq", "Pastika", "Prastama", "Priandana", "Rahayu", "Ramamoorthy", "Ramdoni", "Rubbi", "Seelan", "Shetty", "Surve", "Tadarus", "Tiwari", "Wiswi"]
  },
  "Iran": {
    first: ["Adel", "Ali", "Arshad", "Dad", "Emran", "Hamid", "Masood", "Mehran", "Nader", "Naiem", "Navid", "Yousef"],
    last: ["Abdollahpour", "Balouch", "Bameri", "Dahani", "Dorri", "Hashemi", "Jayezeh", "Kolasangiani", "Mazarzei", "Mohammadipour", "Shadzehisarjou", "Shahbakhsh", "Siasar", "Zahadiafzal"]
  },
  "Ireland": {
    first: ["Alex", "Andre", "Andrew", "Andy", "Barry", "Ben", "Boyd", "Conor", "Craig", "Curtis", "David", "Ed", "Fionn", "Gareth", "Gary", "George", "Graeme", "Graham", "Greg", "Harry", "Jacob", "James", "Jeremy", "John", "Joshua", "Kevin", "Kyle", "Lorcan", "Mark", "Matthew", "Max", "Neil", "Niall", "Nigel", "Paul", "Peter", "Phil", "Regan", "Reinhardt", "Rory", "Ross", "Sean", "Shane", "Simi", "Stephen", "Stuart", "Theo", "Thinus", "Tim", "Trent", "Tyrone", "William"],
    last: ["Adair", "Anderson", "Balbirnie", "Botha", "Bray", "Campher", "Chase", "Connell", "Cusack", "Delany", "Dockrell", "Doheny", "Eaglestone", "Fourie", "Getkate", "Hand", "Hume", "Humphreys", "Johnston", "Jones", "Joyce", "Kane", "Kidd", "Little", "McBrine", "McCallan", "McCann", "McCarter", "McCarthy", "McClintock", "Mooney", "Mulder", "Murtagh", "O'Brien", "Olphert", "Porterfield", "Poynter", "Rankin", "Rock", "Shannon", "Singh", "Sorensen", "Stirling", "Strydom", "Tector", "Terry", "Thompson", "Tucker", "van Woerkom", "West", "White", "Wilson", "Young"]
  },
  "Isle of Man": {
    first: ["Adam", "Alex", "Carl", "Chris", "Christian", "Conor", "Corbin", "Daniel", "Dollin", "Edward", "Fraser", "George", "Jacob", "Jerad", "Joseph", "Josh", "Kieran", "Luke", "Matthew", "Nathan", "Nicholas", "Oliver", "Sam"],
    last: ["Ansell", "Beard", "Burrows", "Butler", "Cawte", "Clarke", "Clough", "Griffin", "Hartmann", "Jansen", "Knights", "Kniveton", "Langford", "Liebenberg", "McAuley", "Mills", "Smith", "Stokoe", "Walker", "Ward", "Webster", "White"]
  },
  "Israel": {
    first: ["Alon", "Amit", "Ari", "Avi", "Barak", "Benjamin", "Daniel", "David", "Doron", "Ehud", "Eitan", "Elad", "Eli", "Emanuel", "Eyal", "Gabriel", "Gal", "Gilad", "Guy", "Idan", "Ilan", "Itai", "Jonathan", "Lior", "Michael", "Moshe", "Nadav", "Natan", "Noam", "Omer", "Ori", "Rafael", "Ram", "Ran", "Ronen", "Sagi", "Samuel", "Shahar", "Tal", "Tomer", "Uri", "Yair", "Yaniv", "Yaron", "Yoav", "Yogev", "Yonatan", "Yuval"],
    last: ["Abramowitz", "Ashkenazi", "Avraham", "Cohen", "Dahan", "Edri", "Feldman", "Friedman", "Golan", "Goldman", "Goldstein", "Harel", "Katz", "Klein", "Levi", "Levy", "Lieberman", "Malka", "Mizrahi", "Naor", "Peretz", "Rosen", "Rosenberg", "Schwartz", "Shapira", "Sharon", "Shemesh", "Solomon", "Stern", "Weiss"]
  },
  "Italy": {
    first: ["Achintha", "Alessandro", "Ali", "Amir", "Anam", "Andy", "Anik", "Anmoldeep", "Anthony", "Baljit", "Bashar", "Benjamin", "Carl", "Charanjeet", "Crishan", "Damian", "Damith", "Dilan", "Dinidu", "Dinuka", "Fida", "Gareth", "Gayashan", "Gian", "Grant", "Gurpreet", "Harry", "Hayden", "Hemantha", "Jade", "Jamie", "Jaspreet", "Joy", "Justin", "Luis", "Madupa", "Manpreet", "Marcus", "Michael", "Nicholas", "Nikolai", "Pathirage", "Peter", "Pidusha", "Rakibul", "Rehman", "Shameera", "Simranjit", "Stefano", "Syed", "Tharindu", "Vince", "Waleed", "Wayne", "Zahid"],
    last: ["Abdul", "Ahmed", "Arachchige", "Berg", "Bonora", "Campopiano", "Cheema", "Crowley", "Denuwan", "Dernbach", "di Bartolomeo", "di Giglio", "Di Venuto", "Fernando", "Grassi", "Hasan", "Hussain", "Jayasena", "Kalugamage", "Khan", "Kosala", "Madsen", "Maiolo", "Manenti", "Marage", "Meade", "Mollik", "Mosca", "Munasinghe", "Naqvi", "Northcote", "Patrizi", "Pennazza", "Perera", "Petricola", "Rana", "Raso", "Ross", "Sadev", "Samarawickrama", "Sandri", "Sharif", "Singh", "Smith", "Stewart"]
  },
  "Japan": {
    first: ["Abdul", "Alester", "Arata", "Benjamin", "Charles", "Declan", "Ibrahim", "Jun", "Kazuma", "Kazumasa", "Kendel", "Kento", "Kiefer", "Kohei", "Koji", "Lachlan", "Makoto", "Marcus", "Masaomi", "Mian", "Naotsune", "Piyush", "Raheel", "Reo", "Rui", "Ryan", "Sabaorish", "Shirai-Patmore", "Shogo", "Supun", "Tomoki", "Tsuyoshi", "Vinay", "Wataru"],
    last: ["Abe", "Dobell", "Drake", "Hinze", "Ito-Davis", "Iyer", "Kadowaki Fleming", "Kadowaki-Fleming", "Kano", "Kato-Stafford", "Kimura", "Kobayashi", "Kubota", "Kumbhare", "Matsumura", "Miyaji", "Miyauchi", "Navaratne", "Ota", "Ravichandran", "Sakurano-Thomas", "Samad", "Siddique", "Suzuki", "Takada", "Takahashi", "Taniyama", "Thurgate", "Ueda", "Wakita", "Yamamoto-Lake", "Yamashita"]
  },
  "Jersey": {
    first: ["Anthony", "Asa", "Ben", "Benjamin", "Charles", "Charlie", "Corey", "Cornelis", "Daniel", "Dominic", "Edward", "Elliot", "George", "Harrison", "Jack", "Jake", "Jonty", "Josh", "Julius", "Nat", "Nick", "Patrick", "Peter", "Rhys", "William", "Zak"],
    last: ["Birrell", "Bisson", "Blampied", "Bodenstein", "Brennan", "Carlyon", "Dunford", "Farley", "Ferraby", "Gouge", "Gough", "Greenwood", "Hawkins-Kay", "Jenner", "Kay", "Kemp", "Kynman", "Lawrenson", "Miles", "Palmer", "Perchard", "Richardson", "Robertson", "Stevens", "Sumerauer", "Tribe", "Ward", "Watkins"]
  },
  "Kenya": {
    first: ["Abdul", "Alex", "Aman", "Brian", "Collins", "David", "Dhiren", "Dominic", "Duncan", "Elijah", "Emmanuel", "Eugene", "Francis", "Gerard", "Gurdeep", "Hiren", "Ibrahim", "Irfan", "Jadavji", "James", "Jasraj", "Jimmy", "Karan", "Kennedy", "Lameck", "Lucas", "Martin", "Maurice", "Narendra", "Nehemiah", "Neil", "Nelson", "Peter", "Pushkar", "Pushpak", "Ragheb", "Rajesh", "Rakep", "Ramesh", "Rushab", "Sachin", "Shem", "Stephen", "Steve", "Sukhdeep", "Tanmay", "Tanzeel", "Thomas", "Tony", "Vishil", "Vraj", "Yash", "Zahid"],
    last: ["Abbas", "Aga", "Akello", "Allan", "Bhudia", "Biko", "Bundi", "Gandhi", "Gill", "Gondaria", "Jesani", "Kalyan", "Kamande", "Karim", "Kaul", "Kerai", "Kituku", "Kundi", "Langat", "Likavu", "Mepani", "Mishra", "Mugabe", "Muthui", "Mutua", "Ngoche", "Obanda", "Obuya", "Ochieng", "Odhiambo", "Odoyo", "Okoth", "Oluoch", "Ongondo", "Onyango", "Otieno", "Ouma", "Patel", "Rehman", "Sharma", "Sheikh", "Singh", "Suji", "Talati", "Tikolo", "Varaiya", "Wesonga"]
  },
  "Kuwait": {
    first: ["Abdul", "Abid", "Adnan", "Ahsan", "Ali", "Aphsal", "Arjun", "Azmatullah", "Bilal", "Clinto", "Diju", "Edson", "Fiaz", "Haroon", "Ilyas", "Imran", "Jandu", "Meet", "Mirza", "Mohamed", "Mohammad", "Mohammed", "Mohomad", "Morshed", "Muhammad", "Naveed", "Nawaf", "Nimish", "Parvindar", "Ravija", "Sajid", "Sanker", "Sayed", "Shahrukh", "Shiraz", "Usman", "Wasantha", "Yasar", "Yasin"],
    last: ["Ahmad", "Ahmed", "Ahsan", "Ali", "Amin", "Ansar", "Anto", "Asghar", "Ashraf", "Aslam", "Bhavsar", "Fakhr", "Hamoud", "Idrees", "Kashif", "Khan", "Kumar", "Kumaranayaka", "Lathief", "Makesh", "Manzil", "Monib", "Mostafa Sarwar", "Mushtaq", "Naseer", "Nazeer", "Patel", "Quddus", "Sadiq", "Sandaruwan", "Shafeeq", "Shahid", "Sheeli", "Silva", "Tahir", "ul Haq", "Umar", "Varathappan", "Waheed", "Zaheer"]
  },
  "Lesotho": {
    first: ["Ajaz", "Ayaj", "Chachole", "Chitja", "Khan", "Lefulere", "Lerotholi", "Maaz", "Mohleki", "Molai", "Mthimkhulu", "Omar", "Riaz", "Sameer", "Sarfaraj", "Shakhele", "Suleman", "Thabiso", "Thamae", "Ts'eliso", "Ts'episo", "Vijayakumar", "Waseem", "Yahya"],
    last: ["Arbaaz", "Chaoana", "Gabriel", "Hussain", "Jakda", "Jayant", "Khan", "Lenyatsa", "Leoela", "Leporoporo", "Letsitsa", "Matsau", "Mohapi", "Monanthane", "Patel", "Ramataboe", "Seth", "Suleman", "Thamae", "Tlali", "Yaqoob"]
  },
  "Luxembourg": {
    first: ["Aanand", "Advyth", "Amit", "Ankush", "Anoop", "Ansh", "Anshuman", "Atif", "Chris", "Eliyas", "Girish", "Harpal", "James", "Jigyasu", "Joost", "Marcus", "Milad", "Mohit", "Pankaj", "Reinhardt", "Richard", "Roshan", "Saransh", "Scott", "Shameek", "Shiv", "Suhail", "Thomas", "Timothy", "Tony", "Vikram", "William"],
    last: ["Barker", "Bhadauria", "Browne", "Cope", "Dhingra", "Dixit", "Fry", "Gill", "Halbhavi", "Heyns", "Jabarkhel", "Kamal", "Kushretha", "Malav", "Manepalli", "Martin", "Mees", "Momend", "Nanda", "Neale", "Orsu", "Pandey", "Pant", "Sadiq", "Trivedi", "Vats", "Venkateswaran", "Vijh", "Virdee", "Vishwanath", "Whiteman"]
  },
  "Malawi": {
    first: ["Aaftab", "Adil", "Alick", "Beston", "Blessings", "Bright", "Chikondi", "Chisomo", "Daniel", "Donnex", "Francis", "Gershom", "Gift", "Hamza", "Irfan", "Kelvin", "Leneck", "Mahammed", "Michael", "Mike", "Moazzam", "Mohamed", "Mohammed", "Muhammad", "Phillip", "Robert", "Sami", "Suhail", "Usama", "Waliyu"],
    last: ["Abdulla", "Baig", "Balala", "Bhima", "Chete", "Choamba", "Jackson", "Jakiel", "Kansonkho", "Kanyandula", "Khurram", "Limdawala", "Masauko", "Master", "Mwamadi", "Nakomo", "Nkhoma", "Ntambalika", "Nurji", "Patel", "Pondani", "Rice", "Sohail", "Thuchila", "Vayani", "Zuze"]
  },
  "Malaysia": {
    first: ["Abdul", "Ahmad", "Ainool", "Aminuddin", "Ammar", "Anwar", "Aqeel", "Aslam", "Bhushan", "Conor", "Dhivendran", "Fitri", "Khizar", "Mohamed", "Muhamad", "Muhammad", "Nazril", "Neville", "Norwira", "Pasha", "Pavandeep", "Rajkumar", "Rizwan", "Saif", "Shafiq", "Sharveen", "Sharvin", "Sivanantha", "Suhan", "Syazrul", "Syed", "Vijay", "Virandeep", "Wan", "Zubaidi"],
    last: ["Alagaratnam", "Amir", "Arief", "Arudin", "Azam", "Aziz", "Faiz", "Hafizs", "Haider", "Haqqiem", "Hayat", "Idrus", "Khan", "Krishnan", "Liyanage", "Mogan", "Muniandy", "Rahman", "Rajendran", "Ramly", "Rashid", "Save", "Sham", "Sharif", "Singh", "Smith", "Surendran", "Syafiq Ali", "Syahadat", "Ullah Malik", "Unni", "Wafiq", "Wahid", "Zazmie", "Zuhdi Hazalan", "Zulkifle"]
  },
  "Maldives": {
    first: ["Abdullah", "Adam", "Ahmed", "Ameel", "Azyan", "Chandana", "Hassan", "Ibrahim", "Ihala", "Ismail", "Kaushal", "Leem", "Mihusan", "Mohamed", "Muaviath", "Nazwan", "Nilantha", "Rasheed", "Savindra", "Shafee", "Shafraz", "Shaof", "Shunan", "Umar", "Wedage"],
    last: ["Adam", "Ali", "Amaradasa", "Azzam", "Cooray", "Farhath", "Ganee", "Hamid", "Hassan", "Ishmath", "Ismail", "Jaleel", "Khalaf", "Kumara", "Liyanage", "Mahfooz", "Malinda", "Mauroof", "Nashath", "Raid", "Rasheed", "Rassam", "Rishwan", "Rizan", "Rodrigo", "Saafee", "Saeed", "Shafeeg", "Shahid"]
  },
  "Mali": {
    first: ["Cheick", "Daouda", "Lamissa", "Lassina", "Mahamadou", "Mamadou", "Mohamed", "Moustapha", "Sanze", "Sekou", "Theodore", "Zakaria"],
    last: ["Berthe", "Coulibaly", "Diaby", "Diakite", "Diawara", "Kamate", "Keita", "Macalou", "Makadji", "Malle", "Sanogo", "Sidibe", "Traore"]
  },
  "Malta": {
    first: ["Aaftab", "Alex", "Amar", "Ashok", "Basil", "Bikram", "Bilal", "Chanjal", "Darshit", "David", "Deon", "Divyes", "Eldhose", "Fanyan", "Fazil", "George", "Gopal", "Haroon", "Hasheem", "Heinrich", "Imran", "Jaison", "Jaspal", "Jitesh", "Jojo", "Jurg", "Justin", "Kalki", "Luke", "Michael", "Micheal", "Niraj", "Niyas", "Noshair", "Nowell", "Pintu", "Ravinder", "Rockey", "Ryan", "Salu", "Samuel", "Sean", "Sobu", "Suhrid", "Sujesh", "Sumair", "Varun", "Waqas", "Washeem", "Yash", "Zeeshan", "Zoheb"],
    last: ["Abbas", "Agius", "Ahmad", "Akhter", "Alam Khan", "Ameer", "Appu", "Aquilina", "Arora", "Bastiansz", "Bishnoi", "Bradley", "Byrne", "Chaturvedi", "Dianish", "George", "Gericke", "Ghosh", "Goonetilleke", "Hirschi", "Jerome", "Khan", "Khanna", "Khosla", "Kumar", "Malek", "Mangat Stanislaus", "Marks", "Mathew", "Meears", "Mughal", "Muhammad", "Nazir", "Patankar", "Patel", "Pullariyil", "Rahman", "Roy", "Shahzad", "Shaju", "Sharma", "Singh", "Sudarsanan", "Thamotharam", "Thomas", "Thomas Kanakalil", "Vosloo"]
  },
  "Mexico": {
    first: ["Alejandro", "Andres", "Antonio", "Carlos", "Cesar", "Daniel", "David", "Diego", "Eduardo", "Emilio", "Enrique", "Fernando", "Francisco", "Gabriel", "Gerardo", "Guillermo", "Gustavo", "Hector", "Hugo", "Jaime", "Jorge", "Jose", "Juan", "Leon", "Luis", "Manuel", "Marco", "Miguel", "Oscar", "Pablo", "Pedro", "Rafael", "Ramiro", "Ricardo", "Roberto", "Rodrigo", "Salvador", "Santiago", "Sergio", "Victor"],
    last: ["Alvarez", "Castillo", "Castro", "Chavez", "Contreras", "Cruz", "Diaz", "Dominguez", "Espinoza", "Flores", "Garcia", "Gomez", "Gonzalez", "Guerrero", "Gutierrez", "Hernandez", "Herrera", "Jimenez", "Lopez", "Luna", "Martinez", "Medina", "Mendoza", "Morales", "Moreno", "Munoz", "Navarro", "Ortiz", "Perez", "Ramirez", "Reyes", "Rivera", "Rodriguez", "Rojas", "Romero", "Ruiz", "Salazar", "Sanchez", "Silva", "Soto", "Torres", "Vargas", "Vazquez", "Vega"]
  },
  "Mongolia": {
    first: ["Buyantushig", "Davaasuren", "Enkh-erdene", "Enkhtuvshin", "Gandemberel", "Hitesh", "Luvsanzundui", "Mohan", "Mungun", "Namsrai", "Nyambaatar", "Od", "Temuulen", "Tumursukh", "Tur", "Tur-erdene", "Zoljavkhlan"],
    last: ["Altankhuyag", "Amarmend", "Bat-yalalt", "Erdenebulgan", "Ganbold", "Jamyansuren", "Lutbayar", "Munkhbat", "Naranbaatar", "Otgonbayar", "Shurentsetseg", "Sumiya", "Sumya", "Terbish", "Turmunkh", "Upadhyay", "Vivekanandan"]
  },
  "Mozambique": {
    first: ["Agostinho", "Alex", "Armando", "Ashish", "Bernardo", "Camate", "Damiao", "Dario", "Farruque", "Filipe", "Frederico", "Gerito", "Gomes", "Imran", "Joao", "Jose", "Kaleem", "Last", "Lourenco", "Louren\u00c3\u00a7o", "Luis", "Mario", "Nelson", "Sanatana", "Shelton", "Vieira", "Zefanias"],
    last: ["Bulele", "Carava", "Chuvale", "Conwana", "Cossa", "Couana", "Dima", "Emilio", "Gomes", "Huo", "Ismail", "Joao", "Koul", "Macome", "Manjate", "Matsinhe", "Mavume", "Navicha", "Nhaduate", "Nhavotso", "Roposo", "Salomone", "Sambo", "Shah", "Simango", "Sopinho", "Tembo"]
  },
  "Myanmar": {
    first: ["Aung", "Aye", "Hein", "Htet", "Khin", "Ko", "Lwin", "Myat", "Nay", "Nyeing", "Paing", "Pyae", "Sai", "Saw", "Swann", "Thuya", "Yan", "Ye"],
    last: ["Aung", "Aye", "Cham Soe", "Danu", "Htet Ko Ko", "Htet Wai", "Ko Ko", "Ko Ko Aung", "Ko Lin Thu", "Lin Aung", "Lin Htun", "Lin Oo", "Maw", "Min Than", "Naing Kyaw", "Naing Tun", "Phyo Wai", "Thu Aung", "Zin Aung"]
  },
  "Namibia": {
    first: ["Alexander", "Andre", "Ben", "Bernard", "Brandon", "Christi", "Christiaan", "Christopher", "Colin", "Craig", "Danie", "David", "Divan", "Dwaine", "Dylan", "Ewald", "Gerhard", "Gerrie", "Gert", "Glenn", "Handre", "Hendrik", "Hermias", "Ian", "Jack", "Jaen", "Jan", "Jan-Izak", "Jason", "Jean", "JJ", "Johan", "Justin", "Karl", "Kobus", "Kola", "Lohan", "Louis", "Malan", "Marius", "Michael", "Michiel", "Mika", "Morne", "N", "Nicol", "Nicolaas", "Nikolaas", "Norbert", "Petrus", "Pieter", "Pikky", "Raymond", "Ricardo", "Ruben", "Sarel", "Shalako", "Shaun", "Simon", "SJ", "Stephan", "Tangeni", "Tiaan", "Tobias", "Tony", "Vernon", "Walter", "Wayne", "Wessel", "Wian", "Willem", "Xander", "Zane", "Zhivago"],
    last: ["Baard", "Balt", "Birkenstock", "Brassell", "Bredenkamp", "Burger", "Busing-Volschenk", "Cloete", "Coombe", "Davidson", "Davin", "de Villiers", "Delport", "Dippenaar", "du Preez", "Engelbrecht", "Erasmus", "Fokkens", "Fouch\u00e9", "Foxcroft", "Frylinck", "Geldenhuys", "Green", "Groenewald", "Grove", "Janse van Rensburg", "Klazinga", "Klazinge", "Kotze", "Kruger", "la Cock", "Leicher", "Loftie-Eaton", "Louw", "Louwrens", "Lungameni", "Manyande", "Mutumbe", "Myburgh", "Nicol Loftie-Eaton", "Opperman", "Palladino", "Peake", "Petrus Shikongo", "Pitchers", "Pretorius", "Raw", "Rossouw", "Rudolph", "Scholtz", "Shikongo", "Smit", "Snyman", "Steenkamp", "Strauss", "Trumpelmann", "van der Westhuizen", "van Lingen", "van Schoor", "van Vuuren", "Verwey", "Viljoen", "Viret", "Wessells", "Wiese", "Williams", "Ya France"]
  },
  "Nepal": {
    first: ["Aarif", "Aasif", "Abinash", "Amrit", "Anil", "Arjun", "Avinash", "Basanta", "Basir", "Bhim", "Bhuvan", "Bibek", "Binod", "Chandra", "Dev", "Dilip", "Dipendra", "Gulsan", "Gyanendra", "Ishan", "Jitendra", "Kamal", "Karan", "Kushal", "Lalit", "Lokesh", "Mahaboob", "Mohammad", "Mousom", "Naresh", "Paras", "Paresh", "Pawan", "Pradeep", "Pratis", "Prithu", "Rajesh", "Rijan", "Rohit", "Sagar", "Sandeep", "Sanjam", "Shahab", "Shakti", "Sharad", "Siddhant", "Sompal", "Subash", "Sundeep", "Sushan"],
    last: ["Aadil Alam", "Ahamad", "Airee", "Alam", "Bam", "Baskota", "Bhandari", "Bhari", "Bhattarai", "Bhurtel", "Bohara", "Budayair", "Dhakal", "Gauchan", "GC", "Jha", "Jora", "Kami", "Karki", "Karn", "KC", "Khadka", "Khakurel", "Khanal", "Lamichhane", "Lohani", "Malla", "Mandal", "Mukhiya", "Nath", "Pandey", "Paudel", "Pulami", "Pun", "Rajbanshi", "Regmi", "Sah", "Sarraf", "Saud", "Sawad", "Sharki", "Sheikh", "Singh Airee", "Vesawkar", "Yadav"]
  },
  "Netherlands": {
    first: ["Ahsan", "Alexei", "Antonius", "Aryan", "Atse", "Bas", "Ben", "Brandon", "Clayton", "Colin", "Daan", "Daniel", "Darron", "Dirk", "Edgar", "Eric", "Fred", "Henk-Jan", "Hidde", "Jeroen", "Julian", "Kyle", "Logan", "Mark", "Max", "Michael", "Mohammad", "Mudassar", "Noah", "Paul", "Peter", "Philippe", "Pieter", "Rahil", "Roelof", "Ryan", "Saqib", "Scott", "Sebastiaan", "Shane", "Shariz", "Sikander", "Stephan", "Sybrand", "Teja", "Thijs", "Tim", "Timm", "Tobias", "Tom", "Vikramjit", "Vivian", "Wesley", "Zach"],
    last: ["Ackermann", "Ahmad", "Ahmed", "Barresi", "Boissevain", "Borren", "Braat", "Bukhari", "Buurman", "Cooper", "Croes", "de Grooth", "de Leede", "de Mey", "Doram", "Dutt", "Edwards", "Engelbrecht", "Floyd", "Glover", "Gruijters", "Heggelman", "Jonkman", "Kashif", "Kervezee", "Kingma", "Klaassen", "Klein", "Levitt", "Lion-Cachet", "Malik", "Mol", "Myburgh", "Nannes", "Nidamanuru", "O'Dowd", "Overdijk", "Pringle", "Reekers", "Rippon", "Schiferli", "Seelaar", "Singh", "Smits", "Snater", "Staal", "Swart", "Szwarczynski", "ten Doeschate", "van Beek", "van Bunge", "van der Gugten", "van der Merwe", "van Meekeren", "van Schelven", "Visee", "Zuiderent", "Zulfiqar"]
  },
  "New Zealand": {
    first: ["Aaron", "Adam", "Adithya", "Ajaz", "Anaru", "Andre", "Andrew", "Andy", "Anton", "Ben", "Benjamin", "BJ", "Blair", "Brendon", "Chad", "Chris", "Cole", "Colin", "Corey", "Craig", "Dane", "Daniel", "Daryl", "Dean", "Devon", "Doug", "Ewen", "Finn", "Gareth", "George", "Glenn", "Graeme", "Grant", "Hamish", "Henry", "Iain", "Ian", "Ish", "Jacob", "James", "Jamie", "Jeetan", "Jeff", "Jesse", "Jimmy", "Josh", "Kane", "Kyle", "Lockie", "Lou", "Luke", "Mark", "Martin", "Mathew", "Matt", "Michael", "Mitchell", "Nathan", "Neil", "Paul", "Peter", "Rachin", "Rob", "Ronnie", "Ross", "Scott", "Seth", "Shane", "Stephen", "Tim", "Todd", "Tom", "Trent", "Will", "William", "Zakary"],
    last: ["Adams", "Aldridge", "Allen", "Anderson", "Ashok", "Astle", "Bates", "Bennett", "Blundell", "Bond", "Boult", "Bowes", "Bracewell", "Broom", "Brownlie", "Bruce", "Butler", "Cairns", "Chapman", "Clarkson", "Cleaver", "Conway", "de Grandhomme", "Devcich", "Diamanti", "Duffy", "Elliott", "Ellis", "Ferguson", "Fleming", "Flynn", "Foulkes", "Foxcroft", "Franklin", "Fulton", "Gillespie", "Guptill", "Hay", "Henry", "Hira", "Hitchcock", "Hopkins", "How", "Ingram", "Jamieson", "Kitchen", "Kuggeleijn", "Latham", "Lister", "Marshall", "Martin", "Mason", "McClenaghan", "McConchie", "McCullum", "McGlashan", "McKay", "McMillan", "Mills", "Milne", "Mitchell", "Munro", "Neesham", "Nicholls", "Nicol", "O'Brien", "Oram", "O\u2019Rourke", "Patel", "Phillips", "Rance", "Ravindra", "Redmond", "Rippon", "Robinson", "Ronchi", "Rutherford", "Ryder", "Santner", "Sears", "Seifert", "Shipley", "Sinclair", "Sodhi", "Southee", "Styris", "Taylor", "Thompson", "Tickner", "Tuffey", "Vettori", "Vincent", "Watling", "Wheeler", "Williamson", "Wilson", "Woodcock", "Worker", "Young", "Younghusband"]
  },
  "Nigeria": {
    first: ["Abiodun", "Abiola", "Ademola", "Akhere", "Ashmit", "Bimbo", "Chibuike", "Chiemelie", "Chima", "Chimezie", "Daniel", "Dotun", "Gershon", "Ifeanyichukwu", "Isaac", "Joshua", "Leke", "Miracle", "Mohameed", "Mojeed", "Mustapha", "Odion", "Olayinka", "Oluseye", "Ovais", "Peter", "Prosper", "Rasheed", "Ridwan", "Saheed", "Samuel", "Segun", "Selim", "Sesan", "Shola", "Sulaimon", "Sylvester", "Vincent"],
    last: ["Abdulkareem", "Abioye", "Abolarin", "Adedeji", "Adewoye", "Adiamo", "Adu", "Aho", "Ajekun", "Akachukwu", "Akhigbe", "Akolade", "Anyia", "Asia", "Ayannaike", "Ayannike", "Danladi", "Gim", "Isesele", "Iteogu", "Mba", "Ogundipe", "Okpe", "Olaleye", "Olatunji", "Olayinka", "Olympio", "Onikoyi", "Onwuzulike", "Oyede", "Runsewe", "Salau", "Shreshta", "Taiwo", "Uboh", "Udekwe", "Useni", "Yousof", "Yusuf"]
  },
  "Norway": {
    first: ["Abdullah", "Ahmadullah", "Ali", "Aminullah", "Ansar", "Bilal", "Chaudhary", "Darshana", "Ehetsham", "Ehtsham", "Faizan", "Hashir", "Hayatullah", "Ibrahim", "Javed", "Junaid", "Khizer", "Muhammad", "Nazakat", "Nouman", "Pratik", "Prithvi", "Qamar", "Rafaqat", "Raza", "Rhys", "Saif-Ul", "Shahbaz", "Sher", "Suhail", "Tafseer", "Usman", "Vinay", "Wahidullah", "Walid", "Waqas"],
    last: ["Abeyrathna", "Agnihotri", "Ahmed", "Akram", "Ali", "Arif", "Bhart", "Butt", "Ghauri", "Hussain", "Iftikhar", "Iqbal", "Islam", "Maroofkhail", "Mehmood", "Mumtaz", "Mushtaque", "Niazi", "Rahimi", "Ravi", "Safdar", "Sahak", "Saleem", "Saunders", "Sheikh", "Shinwari", "Tanha", "Ul Haq", "ul-Haq"]
  },
  "Oman": {
    first: ["Aamer", "Aamir", "Aaqib", "Adnan", "Ajay", "Al", "Amir", "Aqib", "Arun", "Ashish", "Awal", "Ayan", "Bilal", "Farhan", "Fayyaz", "Hammad", "Hemal", "Jatinder", "Jay", "Kaleemullah", "Karan", "Kashyap", "Khalid", "Khawar", "Khurram", "Mehran", "Mohammad", "Munis", "Muzahir", "Naseem", "Nestor", "Pratik", "Rafiullah", "Rajeshkumar", "Samay", "Sandeep", "Shakeel", "Shoaib", "Siddharth", "Sufyan", "Sultan", "Suraj", "Vaibhav", "Vinayak", "Wasim", "Zeeshan"],
    last: ["Ahmed", "Ali", "Ansari", "Athavale", "Bukkapatnam", "Butt", "Dhamba", "Goud", "Ilyas", "Kail", "Kaleem", "Khan", "Khushi", "Kumar", "Lalcheta", "Maqsood", "Mehmood", "Mehta", "Mirza", "Nadeem", "Nawaz", "Odedara", "Odedra", "Poulose", "Prajapati", "Ranpura", "Raza", "Said", "Sanuth", "Shrivastava", "Shukla", "Siddiqui", "Singh", "Sonavale", "Sulehri", "Wategaonkar", "Pallekonda", "Pustoslemsek", "Qureshi", "Sandhu", "Siddiqui", "Singh", "Ujawe"]
  },
  "Pakistan": {
    first: ["Aamer", "Abbas", "Abdul", "Abdullah", "Abdur", "Abrar", "Agha", "Ahmed", "Ahsan", "Aizaz", "Anwar", "Arafat", "Arshad", "Asad", "Asif", "Awais", "Azam", "Azhar", "Babar", "Bilawal", "Danish", "Faheem", "Fakhar", "Fawad", "Haider", "Hammad", "Haris", "Hasan", "Haseebullah", "Hussain", "Iftikhar", "Ihsanullah", "Imad", "Imam-ul-Haq", "Imran", "Inzamam-ul-Haq", "Irfan", "Jahandad", "Junaid", "Kamran", "Khalid", "Khurram", "Khushdil", "Mansoor", "Misbah-ul-Haq", "Mohammad", "Muhammad", "Mukhtar", "Naseem", "Nasir", "Nauman", "Naved-ul-Hasan", "Omair", "Qasim", "Rafatullah", "Rameez", "Raza", "Rumman", "Saad", "Saeed", "Sahibzada", "Saim", "Salman", "Sarfraz", "Shabbir", "Shadab", "Shaheen", "Shahid", "Shahnawaz", "Shahzaib", "Shakeel", "Shan", "Sharjeel", "Shoaib", "Sohaib", "Sohail", "Sufiyan", "Tanvir", "Taufeeq", "Tayyab", "Umar", "Usama", "Usman", "Wahab", "Waqas", "Yasir", "Younis", "Zahid", "Zaman", "Zulfiqar", "Zulqarnain"],
    last: ["Afridi", "Ahmed", "Ajmal", "Akhtar", "Akmal", "Akram", "Alam", "Ali", "Amin", "Amir", "Amjad", "Anjum", "Ansar", "Anwar", "Arafat", "Ashraf", "Asif", "Ayub", "Azam", "Aziz", "Babar", "Bhatti", "Butt", "Cheema", "Dhani", "Farhan", "Farhat", "Gul", "Hafeez", "Haider", "Hameed", "Haris", "Hasan", "Hasnain", "Iqbal", "Irfan", "Jamal", "Jamshed", "Khalil", "Khan", "Latif", "Mahmood", "Malik", "Manzoor", "Maqsood", "Masood", "Minhas", "Mir", "Mohmand", "Muqeem", "Musa", "Nasim", "Nawaz", "Nazir", "Qadir", "Raees", "Raja", "Rauf", "Razzaq", "Rehman", "Riaz", "Rizwan", "Salman", "Sami", "Shafiq", "Shafique", "Shah", "Shehzad", "Sohail", "Tahir", "Talat", "Tanvir", "Umar", "Wasim", "Yamin", "Yousuf", "Zaman", "Zia"]
  },
  "Panama": {
    first: ["Abdiel", "Alberto", "Alejandro", "Alfredo", "Andres", "Antonio", "Arnulfo", "Bolivar", "Carlos", "Cesar", "Daniel", "David", "Eduardo", "Enrique", "Ernesto", "Felipe", "Fernando", "Francisco", "Gabriel", "Gonzalo", "Gustavo", "Hector", "Hugo", "Jaime", "Jorge", "Jose", "Juan", "Luis", "Manuel", "Marco", "Mario", "Miguel", "Omar", "Pablo", "Pedro", "Rafael", "Ricardo", "Roberto", "Rodrigo", "Santiago", "Sergio", "Tomas", "Victor"],
    last: ["Arauz", "Batista", "Caballero", "Castillo", "Castro", "Cedeno", "Chavez", "Cordoba", "De Leon", "Diaz", "Dominguez", "Espino", "Fernandez", "Flores", "Garcia", "Gonzalez", "Guerra", "Gutierrez", "Hernandez", "Herrera", "Jimenez", "Lopez", "Martinez", "Medina", "Mendoza", "Morales", "Moreno", "Munoz", "Navarro", "Nunez", "Ortega", "Ortiz", "Perez", "Pineda", "Quintero", "Ramirez", "Rios", "Rodriguez", "Romero", "Ruiz", "Sanchez", "Santos", "Soto", "Torres", "Vargas", "Vasquez", "Vergara"]
  },
  "Papua New Guinea": {
    first: ["Alei", "Andrew", "Asad", "Chad", "Charles", "Chris", "Christopher", "Damien", "Dogodo", "Geraint", "Hila", "Hiri", "Hitolo", "Jack", "Jason", "Joel", "John", "Kabua", "Kila", "Kiplin", "Lega", "Loa", "Mahuru", "Michael", "Norman", "Nosaina", "Pipi", "Rarva", "Riley", "Semo", "Sese", "Simon", "Steven", "Tony", "Vani", "Willie"],
    last: ["Amini", "Areni", "Atai", "Bau", "Charlie", "Dai", "Dikana", "Doriga", "Eno", "Gardner", "Gavera", "Hekure", "Hicks", "Hiri", "Jones", "Kamea", "Kariko", "Kent", "Kila", "Morea", "Nao", "Nou", "Pala", "Pokana", "Raho", "Ravu", "Reva", "Siaka", "Soper", "Tom", "Ura", "Vala", "Vanua", "Vare"]
  },
  "Peru": {
    first: ["Christopher", "D", "Hafez", "Jagjit", "Joaquin", "Matthew", "Mohsin", "Oliver", "Pravin", "Shaikh", "Steven", "Suresh", "Waqar"],
    last: ["Ashraf", "de la Puente", "Farooq", "Hallett", "Hub", "Khan", "Kumar", "Mahoney", "Marshall", "Salazar", "Shamdasani", "Singh", "Spry"]
  },
  "Philippines": {
    first: ["Adrian", "Andrew", "Angelo", "Antonio", "Bryan", "Carlos", "Christian", "Daniel", "David", "Francis", "Gabriel", "James", "Jason", "Jerome", "John", "Jose", "Joseph", "Joshua", "Juan", "Kevin", "Luis", "Marco", "Mark", "Michael", "Miguel", "Patrick", "Paulo", "Rafael", "Richard", "Ryan"],
    last: ["Aguilar", "Aquino", "Bautista", "Castro", "Cruz", "Dela Cruz", "Diaz", "Fernandez", "Flores", "Garcia", "Gonzales", "Hernandez", "Lim", "Lopez", "Mendoza", "Mercado", "Morales", "Navarro", "Pascual", "Ramos", "Reyes", "Rivera", "Rodriguez", "Santos", "Santiago", "Soriano", "Tan", "Tolentino", "Torres", "Villanueva"]
  },
  "Portugal": {
    first: ["Aamer", "Ali", "Amandeep", "Amir", "Anthony", "Arslan", "Assad", "Azhar", "Fakhrul", "Francoise", "Ghazanfar", "Imran", "Intesab", "Jiteshkumar", "Junaid", "Khalid", "Kuldeep", "Mian", "Miguel", "Mubeen", "Nadeem", "Najjam", "Paolo", "Rahul", "Rizwan", "Sharn", "Sirajullah", "Sukhwinder", "Suman", "Surinder", "Syed", "Tariq", "Umar", "Zohaib", "Zulfiqar"],
    last: ["Ahmed", "Ali", "Ali Shah", "Andani", "Aziz", "Balkrisna", "Bhardwaj", "Buccimazza", "Butt", "Chambers", "Farooq", "Ghimire", "Gomes", "Ikram", "Izaz", "Khadim", "Khaliq", "Khan", "Machado", "Maisam Ali", "Medhi", "Mehmood", "Mohon", "Naqi", "Naseem", "Sarwar", "Shahzad", "Sharma", "Singh", "Stoman", "Tariq", "Zaib"]
  },
  "Qatar": {
    first: ["Adnan", "Akash", "Amir", "Andri", "Arumugaganesh", "Assad", "Awais", "Bipin", "Bukhar", "Dharmang", "Faisal", "Gayan", "Himanshu", "Ikramullah", "Imal", "Imran", "Inam-ul-Haq", "Iqbal", "Jassim", "Kamran", "Khurram", "Mirza", "Mohammad", "Mohammed", "Muhammad", "Mujeeb-ur-Rehman", "Musawar", "Nouman", "Qalandar", "Saqlain", "Syed", "Tamoor", "Uzair", "Valeed", "Yousuf", "Zaheer"],
    last: ["Ahnaff", "Ali", "Amir", "Arshad", "Ashraf", "Asim", "Babu", "Berenger", "Borham", "Farooq", "Hussain", "Ibrahim", "Illikkal", "Irshad", "Jabir", "Javed", "Khan", "Kumar", "Liyanage", "Malik", "Mirza", "Mohammed Baig", "Munaweera", "Murad", "Nadeem", "Nagarajan", "Patel", "Rathod", "Rizlan", "Sajjad", "Sarwar", "Shah", "Shahzad", "Tameem", "Tanveer", "Veetil"]
  },
  "Romania": {
    first: ["Abdul", "Aftab", "Asif", "Cosmin", "Dharmendra", "Gaurav", "Gohar", "Ijaz", "Imran", "Laurentiu", "Manmeet", "Marian", "Patras", "Pavel", "Petre", "Rajendra", "Rajesh", "Ramesh", "Rohit", "Sadeeq", "Sami", "Satvik", "Senthilvel", "Shantanu", "Sivakumar", "Sudeep", "Sukhkaran", "Taranjeet", "Vasu", "Waqar"],
    last: ["Abbasi", "Bevinje", "Danci", "Florin", "Gharasim", "Gherasim", "Haider", "Hussain", "Karthikeyan", "Kayani", "Khan", "Koli", "Kumar", "Manan", "Manani", "Masih", "Mishra", "Nadigotla", "Periyalwar", "Pisal", "Sahi", "Saini", "Satheesan", "Shakoor", "Singh", "Thakur", "Ullah", "Vashisht", "Zavoiu"]
  },
  "Rwanda": {
    first: ["Aime", "Babar", "Bashir", "Bosco", "Byrson", "Clinton", "Daniel", "David", "Didier", "Emile", "Emmanuel", "Eric", "Freddy", "Ignace", "Isae"],
    last: ["Akayezu", "Ali", "Bimenyimana", "Bugingo", "Cyusa", "Dusabemungu", "Dusingizimana", "Gumyusenge", "Hakizimana", "Iradukunda", "Irakoze", "Kubwimana", "Manishimwe", "Mira", "Mitari", "Mucyodusenge", "Mugisha", "Nadir", "Ndayisenga", "Ndikubwimana", "Niyitanga", "Niyomugabo", "Ntirenganya", "Pierre", "Rububagumya", "Rukiriza", "Samal", "Sebareme", "Songa", "Tuyisenge", "Tuyizere", "Uwimana", "Vekaria"]
  },
  "Samoa": {
    first: ["Andrew", "Benjamin", "Bismarck", "Caleb", "Daniel", "Darren", "Dom", "Dominic", "Douglas", "Fa'afetaialealofa", "Faasao", "Fereti", "Fred", "James", "Lester", "Maletino", "Naa", "Ofisa", "Samson", "Saumani", "Sean", "SM", "Uala", "Uili"],
    last: ["Baker", "Burgess", "Cotter", "Evile", "Finau", "Jasmat", "Kaisala", "Maiava", "Mailata", "Michael", "Mulivai", "Roache", "Sapatu", "Schuster", "Sofi", "Sola", "Solia", "Suluoto", "Tiai", "Tonuu", "Vaaetasi", "Vaasili"]
  },
  "Saudi Arabia": {
    first: ["Abbas", "Abdul", "Adil", "Afaq", "Ahmad", "Ahmed", "Ali", "Amir", "Atif-Ur-Rehman", "Choudhry", "Faisal", "Haseeb", "Hisham", "Ibrahim", "Ibrarul", "Ihsan", "Imran", "Inayat", "Irfan", "Irshad", "Ishtiaq", "Kashif", "Khalander", "Khawar", "Manan", "Mohammad", "Mohsin", "Muhammad", "Nawazish", "Saad", "Sajid", "Sarfraz", "Shahbaz", "Shahzaib", "Shamsudheen", "Shoaib", "Sidharth", "Umair", "Usman", "Waji", "Waqar", "Zain", "Zeeshan", "Zuber", "Zuhair"],
    last: ["Abbas", "Adnan", "Afzal", "Ahmad", "Ahmed", "Akhtar", "Ali", "Arif", "Baladraf", "Butt", "Cheema", "Ghafoor", "Hamayun", "Haq", "Jezuli", "Khalid", "Khan", "Md Imran", "Mubbashar", "Muhammad", "Mustafa", "Nadeem", "Naeem", "Najeeb", "Purat", "Rasheed", "Raza", "Saad", "Saeed", "Sankar", "Saqib", "Sarfraz", "Shabbir", "Shahzad", "Sharif", "Sheikh", "Siddique", "Sunasara", "Ul Abidin", "Ul Hassan", "Ullah", "Waheed", "Wahid", "Yousaf", "Yousuf", "Zafar"]
  },
  "Scotland": {
    first: ["Adrian", "Alasdair", "Brad", "Bradley", "Brandon", "Calum", "Calvin", "Charlie", "Chris", "Colin", "Con", "Craig", "David", "Dewald", "Dougie", "Dylan", "Fraser", "Freddie", "Gavin", "George", "Glenn", "Gordon", "Gregor", "Hamza", "Iain", "Jack", "Jan", "Jasper", "John", "Josh", "Kyle", "Majid", "Marc", "Mark", "Matt", "Matthew", "Michael", "Moneeb", "Navdeep", "Neil", "Ollie", "Preston", "Richie", "Robert", "Ross", "Ruaidhri", "Ryan", "Safyaan", "Simon", "Stuart", "Tom", "Tomas", "Tyler"],
    last: ["Berrington", "Blain", "Brown", "Buchan", "Budge", "Burnett", "Carter", "Cassell", "Coetzer", "Coleman", "Cross", "Currie", "Davey", "Davidson", "de Lange", "Drummond", "Evans", "Flannigan", "Goudie", "Greaves", "Hairs", "Hamilton", "Haq", "Iqbal", "Jarvis", "Jones", "Leask", "Lyons", "Machan", "Mackintosh", "MacLeod", "Maiden", "Main", "McCallum", "McMullen", "Mommsen", "Munsey", "Murphy", "Neill", "Nel", "Parker", "Petrie", "Poonia", "Rogers", "Sharif", "Smith", "Sole", "Stander", "Tahir", "Taylor", "Tear", "Wallace", "Wardlaw", "Watson", "Watt", "Watts", "Wheal", "Whittingham", "Wright"]
  },
  "Serbia": {
    first: ["Aleksa", "Alexander", "Alister", "Apon", "Ayo", "Bilal", "Bogdan", "Brett", "Danijel", "Djordje", "Haris", "Ivan", "Jovan", "Leslie", "Luka", "Mark", "Matija", "Matthew", "Michael", "Nemanja", "Nicholas", "Peter", "Rahman", "Rhys", "Robin", "Sachin", "Sakib", "Simo", "Slobodan", "Stefan", "Vukasin", "Wintley"],
    last: ["Ademi", "Ahmed", "Burton", "Civric", "Dajc", "Davidson", "Dizija", "Djorovic", "Dorgan", "Dugic", "Dunbar", "Gajic", "Hartley", "Hasan", "Ivetic", "Johns-Wickberg", "Kostic", "Mene-Ejegi", "Mustafizur", "Nedeljkovic", "Nerandzic", "Pavlovic", "Petrovic", "Reb", "Sarenac", "Shinde", "Tosic", "Tresac", "Vitas", "Woods", "Zimonjic"]
  },
  "Seychelles": {
    first: ["Adam", "Allan", "Andre", "Andy", "Bertrand", "Brian", "Chris", "Daniel", "Darren", "David", "Dean", "Dylan", "Edmond", "Emmanuel", "Felix", "Gerard", "Gilbert", "Jean", "Joel", "John", "Keith", "Kevin", "Liam", "Marcel", "Mark", "Martin", "Michael", "Noel", "Oliver", "Patrick", "Paul", "Peter", "Philippe", "Pierre", "Ralph", "Ricky", "Robert", "Rodney", "Ryan", "Simon", "Stephen", "Thierry", "Thomas", "Xavier"],
    last: ["Adelaide", "Albert", "Azemia", "Barbe", "Belmont", "Bonaparte", "Bristol", "Camille", "Charlot", "Decomarmond", "Desnousse", "Esparon", "Figaro", "Florentine", "Gabriel", "Gardette", "Hoareau", "Jean", "Joubert", "Labrosse", "Laurence", "Marie", "Mondon", "Morel", "Moustache", "Nalletamby", "Payet", "Pillay", "Pool", "Radegonde", "Regar", "Rose", "Savy", "Sinon", "Valentin", "Woodcock"]
  },
  "Sierra Leone": {
    first: ["Abass", "Abu", "Alusine", "Aruna", "Arvind", "Chernoh", "Edmond", "Edward", "George", "Hari", "Ibrahim", "John", "Lansana", "Miniru", "Mohamed", "Mohammad", "Moses", "Osman", "Raymond", "Richard", "Samuel", "Solomon", "Sulaiman", "Yegbeh", "Zahid"],
    last: ["Bah", "Bangura", "Coker", "Conteh", "Ernest", "Gbla", "Jalloh", "Kainessie", "Kamara", "Kerai", "Khan", "Kpaka", "Lamin", "Mansaray", "Ngegba", "Ram Bhamu", "Sankoh", "Sesay", "Shamshad Khan", "Tarawally", "Tommy", "Turay", "Williams"]
  },
  "Singapore": {
    first: ["Alvin", "Anand", "Brandon", "Calvin", "Chee", "Darren", "Derrick", "Gabriel", "Hafiz", "Hao", "Imran", "Jason", "Jeremy", "Jin", "Jun", "Kai", "Kenneth", "Kumar", "Marcus", "Muhammad", "Nicholas", "Raj", "Ravi", "Ryan", "Samuel", "Shawn", "Siva", "Suresh", "Timothy", "Victor", "Wei", "Weng", "Xian", "Yew", "Zheng"],
    last: ["Ahmad", "Chan", "Chen", "Chua", "Fernando", "Goh", "Ho", "Ibrahim", "Ismail", "Koh", "Kumar", "Lee", "Lim", "Lin", "Menon", "Nair", "Ng", "Ong", "Perera", "Pillai", "Prakash", "Rajah", "Raman", "Seah", "Sharma", "Singh", "Tan", "Tay", "Teo", "Wong", "Yeo", "Yong"]
  },
  "Slovenia": {
    first: ["Ales", "Andrej", "Blaz", "Bojan", "Bostjan", "David", "Dejan", "Filip", "Gasper", "Gregor", "Igor", "Jan", "Jure", "Klemen", "Luka", "Marko", "Matej", "Matjaz", "Miha", "Nejc", "Nik", "Peter", "Rok", "Simon", "Tilen", "Tim", "Tomaz", "Uros", "Vid", "Zan"],
    last: ["Bizjak", "Breznik", "Cerne", "Filipic", "Golob", "Horvat", "Hribar", "Jerman", "Kolar", "Kos", "Kotnik", "Kovac", "Kovacic", "Krajnc", "Kranjc", "Levstek", "Mlakar", "Novak", "Oblak", "Potocnik", "Praprotnik", "Rozman", "Strukelj", "Tomazic", "Turk", "Vidmar", "Zagar", "Zajc", "Zupan"]
  },
  "South Africa": {
    first: ["Aaron", "AB", "Aiden", "Albie", "Alfonso", "Alviro", "Andile", "Andre", "Andrew", "Anrich", "Ashwell", "Beuran", "Bjorn", "Boeta", "Charl", "Chris", "Christiaan", "Colin", "Dale", "Dane", "David", "Dayyaan", "Dewald", "Donavon", "Dwaine", "Eddie", "Faf", "Farhaan", "Garnett", "George", "Gerald", "Gihahn", "Glenton", "Graeme", "Gulam", "Hashim", "Heino", "Heinrich", "Henry", "Herschelle", "Imran", "Jacques", "Janneman", "Jason", "Jean-Paul", "JJ", "Johan", "Johann", "Junior", "Justin", "Kagiso", "Keshav", "Kwena", "Kyle", "Lizaad", "Lonwabo", "Loots", "Lungi", "Lutho", "Makhaya", "Mangaliso", "Marchant", "Marco", "Mark", "Matthew", "Monde", "Morne", "Nandre", "Neil", "Nicky", "Nqabayomzi", "Ottniel", "Patrick", "Pite", "Quinton", "Rassie", "Reeza", "Richard", "Rilee", "Robert", "Robin", "Roelof", "Roger", "Rory", "Rusty", "Ryan", "Shaun", "Sinethemba", "Sisonda", "Tabraiz", "Temba", "Theunis", "Tristan", "Tyron", "Vaughn", "Vernon", "Wayne", "Wihan", "Willem", "Yusuf"],
    last: ["Abbott", "Abdulla", "Amla", "Baartman", "Bavuma", "Behardien", "Bodi", "Boje", "Bosman", "Botha", "Boucher", "Breetzke", "Brevis", "Burger", "Cloete", "Coetzee", "Dala", "Davids", "de Bruyn", "de Kock", "de Lange", "de Villiers", "Dippenaar", "du Plessis", "Duminy", "Ferreira", "Fortuin", "Frylinck", "Galiem", "Gibbs", "Hall", "Henderson", "Hendricks", "Ingram", "Jansen", "Jonker", "Kallis", "Kemp", "Klaasen", "Kleinveldt", "Kruger", "Kuhn", "Langeveldt", "Leie", "Levi", "Linde", "Louw", "Lubbe", "Magala", "Maharaj", "Malan", "Maphaka", "Markram", "McKenzie", "McLaren", "Miller", "Morkel", "Morris", "Mosehle", "Mulder", "Nel", "Ngidi", "Nortje", "Ntini", "Ontong", "Parnell", "Paterson", "Peter", "Petersen", "Peterson", "Phangiso", "Phehlukwayo", "Philander", "Pollock", "Pretorius", "Prince", "Qeshile", "Rabada", "Rickelton", "Rossouw", "Rudolph", "Shamsi", "Simelane", "Sipamla", "Smith", "Smuts", "Snyman", "Steyn", "Stubbs", "Stuurman", "Tahir", "Telemachus", "Theron", "Thomas", "Tsotsobe", "van Biljon", "van der Dussen", "van der Merwe", "van der Wath", "van Jaarsveld", "van Wyk", "Vilas", "Wiese", "Williams", "Zondeki"]
  },
  "South Korea": {
    first: ["Byeongho", "Changmin", "Cheol", "Daewon", "Donghyun", "Geunwoo", "Gwangmin", "Haneul", "Hyeok", "Hyun", "Insoo", "Jaehyun", "Jiho", "Jinho", "Jinwoo", "Jongmin", "Jun", "Junhyeok", "Junho", "Kihyeon", "Minho", "Myeongwoo", "Sanghyeok", "Seonghyun", "Seungmin", "Seungwoo", "Sunghyun", "Taeyang", "Wonjin", "Yejun", "Yonghwan", "Yongseok", "Yunho"],
    last: ["Ahn", "Bae", "Baek", "Cho", "Choi", "Chung", "Han", "Hong", "Hwang", "Jang", "Jeon", "Jeong", "Jo", "Kang", "Kim", "Ko", "Kwon", "Lee", "Lim", "Moon", "Na", "Oh", "Park", "Ryu", "Seo", "Shin", "Son", "Song", "Yang", "Yoo", "Yoon", "Yu"]
  },
  "Spain": {
    first: ["Alejandro", "Alvaro", "Andres", "Antonio", "Carlos", "Daniel", "David", "Diego", "Eduardo", "Enrique", "Felipe", "Fernando", "Francisco", "Gabriel", "Gonzalo", "Hector", "Hugo", "Ivan", "Javier", "Jorge", "Jose", "Juan", "Luis", "Manuel", "Marco", "Mario", "Miguel", "Nicolas", "Oscar", "Pablo", "Pedro", "Rafael", "Ramon", "Ricardo", "Roberto", "Rodrigo", "Santiago", "Sergio", "Vicente", "Victor"],
    last: ["Alvarez", "Blanco", "Caballero", "Castillo", "Castro", "Cortes", "Cruz", "Delgado", "Diaz", "Dominguez", "Fernandez", "Flores", "Garcia", "Gomez", "Gonzalez", "Guerrero", "Gutierrez", "Hernandez", "Jimenez", "Lopez", "Martinez", "Medina", "Molina", "Morales", "Moreno", "Munoz", "Navarro", "Ortega", "Ortiz", "Perez", "Ramirez", "Reyes", "Rivera", "Rodriguez", "Romero", "Ruiz", "Sanchez", "Santos", "Serrano", "Soto", "Torres", "Vargas", "Vega"]
  },
  "Sri Lanka": {
    first: ["Ajantha", "Akila", "Amila", "Angelo", "Asela", "Ashan", "Ashen", "Asitha", "Avishka", "Bhanuka", "Binura", "Chamara", "Chamika", "Chaminda", "Chamindu", "Chanaka", "Charith", "Chaturanga", "Chinthaka", "Dasun", "Dhammika", "Dhananjaya", "Dhanushka", "Dilhara", "Dilruwan", "Dilshan", "Dinesh", "Dunith", "Dushmantha", "Farveez", "Gayan", "Gihan", "Indika", "Isuru", "Janith", "Jeevan", "Jeevantha", "Jeffrey", "Jehan", "Kamil", "Kamindu", "Kasun", "Kaushal", "Kaushalya", "Kithuruwan", "Kumar", "Kusal", "Kushal", "Lahiru", "Lakshan", "Lasith", "Maheesh", "Mahela", "Malinga", "Marvan", "Matheesha", "Milinda", "Minod", "Muthumudalige", "Muttiah", "Niroshan", "Nuwan", "Nuwanidu", "Oshada", "Pathum", "Pramod", "Praveen", "Ramesh", "Ramith", "Rangana", "Ruchira", "Russel", "Sachith", "Sachithra", "Sadeera", "Sanath", "Seekkuge", "Shaminda", "Shehan", "Suraj", "Suranga", "Thikshila", "Thilan", "Thilina", "Thisara", "Tillakaratne", "Upul", "Vishwa", "Wanindu", "Wikum"],
    last: ["Aponso", "Arnold", "Asalanka", "Atapattu", "Bandara", "Bhanuka", "Chameera", "Chandimal", "Dananjaya", "de Saram", "de Silva", "Dickwella", "Dilshan", "Eranga", "Fernando", "Gunaratne", "Gunathilleke", "Hasaranga", "Herath", "Janith Perera", "Jayasinghe", "Jayasuriya", "Jayawardene", "Jayawickrama", "Kandamby", "Kapugedera", "Karunaratne", "Kulasekara", "Kulatunga", "Kumara", "Lakmal", "Liyanage", "Lokuarachchi", "Lokuhettige", "Madushan", "Madushanka", "Maharoof", "Malinga", "Mathews", "Mendis", "Mishara", "Mubarak", "Munaweera", "Muralitharan", "Nissanka", "Pathirana", "Perera", "Pradeep", "Prasad", "Prasanna", "Priyanjan", "Pushpakumara", "Rajapaksa", "Rajitha", "Rambukwella", "Randiv", "Rupasinghe", "Samarawickrama", "Sandakan", "Sangakkara", "Sanjaya", "Senanayake", "Shanaka", "Silva", "Siriwardana", "Tharanga", "Theekshana", "Thirimanne", "Thushara", "Udana", "Udawatte", "Vaas", "Vandersay", "Vithanage", "Weeraratne", "Welegedara", "Wellalage", "Wickramasinghe", "Wijekoon"]
  },
  "St Helena": {
    first: ["Aiden", "Alex", "Andrew", "Barry", "Branden", "Brett", "Christian", "Cliff", "Damien", "Darrell", "David", "Dax", "Gareth", "Jamie", "Jordi", "Nico", "Phillip", "Rhys", "Ryan", "Scott"],
    last: ["Belgrove", "Crowie", "Ellick", "Francis", "George", "Henry", "Isaac", "Johnson", "Langham", "Leo", "O'Bey", "Richards", "Stroud", "Yon", "Young"]
  },
  "Swaziland": {
    first: ["Adil", "Alexander", "Buhle", "Christiaan", "Delisa", "Dinesh", "Eric", "Frederick", "Hamilton", "Haris", "Imran", "Jawad", "Joseph", "Juber", "Junain", "Lindinkosi", "Loyiso", "Mancoba", "Melusi", "Mohammed", "Mohsin", "Muhammad", "Musa", "Naeem", "Phumlani", "Roy", "Shahzad", "Shehzad", "Sibusiso", "Siphesihle", "Sohail", "Tahir", "Tarun", "Tehseen", "Umair", "Wandile"],
    last: ["Akhtar", "Alamgir", "Amin", "Butt", "Chester", "Chirwa", "Dlamini", "Forbes", "Ghadiyali", "Gull", "Hansrod", "Hassan", "Jele", "Khan", "Kubheka", "Magagula", "Mahmood", "Malinga", "Mucyo", "Muhammad", "Nicholas", "Nyakatawa", "Patel", "Phiri", "Polpitiya", "Qasim", "Rashid", "Sandeep", "Sibiya", "Twala", "Wright", "Zulu"]
  },
  "Sweden": {
    first: ["Alexander", "Anders", "Anton", "Axel", "Bjorn", "Daniel", "David", "Elias", "Emil", "Erik", "Felix", "Fredrik", "Gustaf", "Gustav", "Henrik", "Hugo", "Johan", "Jonas", "Karl", "Lars", "Leif", "Linus", "Magnus", "Marcus", "Mattias", "Mikael", "Niklas", "Nils", "Olof", "Oskar", "Patrik", "Per", "Simon", "Stefan", "Sven", "Tobias", "Viktor"],
    last: ["Andersson", "Bengtsson", "Berglund", "Bergman", "Bergstrom", "Bjork", "Eklund", "Engstrom", "Eriksson", "Forsberg", "Fransson", "Gustafsson", "Hansson", "Hedlund", "Holm", "Holmberg", "Jansson", "Johansson", "Jonsson", "Karlsson", "Larsson", "Lindberg", "Lindgren", "Lindqvist", "Lindstrom", "Lundin", "Lundqvist", "Mattsson", "Nilsson", "Nordstrom", "Nystrom", "Olsson", "Persson", "Pettersson", "Sandberg", "Sjoberg", "Sundberg", "Svensson", "Wallin"]
  },
  "Switzerland": {
    first: ["Adrian", "Alain", "Alexander", "Andreas", "Beat", "Bruno", "Christian", "Christoph", "Claude", "Daniel", "David", "Dominik", "Eric", "Fabien", "Fabian", "Felix", "Florian", "Hans", "Jan", "Jonas", "Julien", "Lars", "Luca", "Lukas", "Marc", "Marco", "Markus", "Martin", "Mathieu", "Matthias", "Michael", "Nicolas", "Niklaus", "Oliver", "Pascal", "Patrick", "Peter", "Philippe", "Raphael", "Remo", "Rene", "Roger", "Roman", "Samuel", "Simon", "Stefan", "Stephan", "Thomas", "Urs"],
    last: ["Aebischer", "Ammann", "Bachmann", "Baumann", "Berger", "Berner", "Brunner", "Bucher", "Egli", "Frei", "Gerber", "Graf", "Huber", "Keller", "Koch", "Kunz", "Lang", "Lehmann", "Maurer", "Meier", "Meyer", "Moser", "Mueller", "Muller", "Peter", "Schmid", "Schmidt", "Schneider", "Steiner", "Studer", "Wagner", "Weber", "Widmer", "Wirth", "Wolf", "Wyss", "Zimmermann", "Zuercher"]
  },
  "Tanzania": {
    first: ["Aaryan", "Abdallah", "Abduramani", "Abhik", "Akhil", "Ally", "Amal", "Arshan", "Ashish", "Dhrumit", "Harsh", "Harsheed", "Ivan", "Jatin", "Jatinkumar", "Jitin", "Johnson", "Kassim", "Khalil", "Mohamed", "Muhammad", "Nasibu", "Omary", "R", "Riziki", "Salum", "SanjayKumar", "Shaik", "Yalinde", "Zamoyoni"],
    last: ["Ally", "Amarshi", "Anil", "Basha", "Chandubhai", "Chohan", "Darji", "Hussein", "Issa", "Jabiri", "Jaboneke", "Jasani", "Jumbe", "Kamania", "Kimote", "Kiseto", "Kitunda", "Mapunda", "Mehta", "Mussa", "Nassoro", "Nkanya", "Nyambo", "Patwa", "Premji", "Rajeevan", "Ramaiya", "Rehmtullah", "Selemani", "Singh", "Thakor", "Zafar Khan"]
  },
  "Thailand": {
    first: ["Akshaykumar", "Anowarul", "Anucha", "Austin", "Chaloemwong", "Chanchai", "Daniel", "Henno", "Ismail", "Jandre", "Jeerasak", "Kamron", "Khanitson", "Kiatiwut", "Mahsid", "Md", "Mukesh", "Narawit", "Naveed", "Nicholas", "Nopphon", "Panuwat", "Payuputh", "Phanuphong", "Phiriyapong", "Robert", "Sarawut", "Satarut", "Sittipong", "Sorawat", "Thanadon", "Thanaphon", "Vichanath", "Wanchana", "Wiraphan", "Yodsak", "Ziaul"],
    last: ["Buree", "Chatphaisan", "Coetzee", "Desungnoen", "Faheem", "Hongsi", "Hoque", "Islam", "Jacobs", "Janes", "Jordaan", "Kalasi", "Lazarus", "Maliwan", "Namchaikul", "Ngowhuad", "Nuntarach", "Pakhiaokajee", "Pathan", "Pengkumta", "Raina", "Rungrueang", "Saranonnakkun", "Sardar", "Senamontree", "Shafiqul Haque", "Singh", "Suanchuai", "Sungnard", "Suttisan", "Thakur", "Thongsa", "Uisuk", "Yadav", "Yotharat"]
  },
  "Turkey": {
    first: ["Ahmet", "Ali", "Batuhan", "Cagri", "Cengiz", "Cihan", "Deni?z", "Emi?n", "Gokhan", "Hasan", "Ilyas", "Ishak", "Mecit", "Mehmat", "Mehmet", "Muhammed", "Muhammet", "Murat", "Osman", "Recep", "Romeo", "Serdar", "Serkan", "Shamsullah", "Tunahan", "Zafer"],
    last: ["Aky\u00c3\u00bcz", "Alta", "Altun", "Ataullah", "Bayraktar", "Bicer", "Cakir", "Durmaz", "Dursak", "Ehsan", "Elec", "Goker", "Helva", "Ipek", "Kansoy", "Kizilkaya", "Kose", "Ko\u00c3\u00a7", "Kursat", "Kuyumcu", "Mutu", "Nath", "Ozturk", "Sahin", "Sert", "Turan", "Turkmen", "Ulutuna", "Yilmaz"]
  },
  "Uganda": {
    first: ["Abram", "Akbar", "Alpesh", "Arnold", "Arthur", "Asadu", "Benjamin", "Bilal", "Brian", "Charles", "Cosmas", "Cyrus", "David", "Davis", "Dennis", "Deusdedit", "Dinesh", "Emmanuel", "Frank", "Fred", "Gerald", "Hamu", "Hamza", "Henry", "Irfan", "Ismail", "Ivan", "Jeremy", "Joel", "Jonathan", "Joseph", "Juma", "Kenneth", "Lawrence", "Martin", "Moses", "Mpho", "Nand", "Nicholas", "Pascal", "Patrick", "Raghav", "Raymond", "Riazat", "Richard", "Robinson", "Roger", "Rogers", "Ronak", "Ronald", "Santos", "Saud", "Shrideep", "Simon", "Siraje", "Trevor", "Zephania"],
    last: ["Achelam", "Afridi", "Agamiire", "Akankwasa", "Ali Shah", "Arinaitwe", "Bagenda", "Baguma", "Baig", "Bukenya", "Dhawan", "Hasahya", "Hassun", "Isabirye", "Isaneez", "Islam", "Kakuru", "Kamyuka", "Kayondo", "Kebba", "Kibukamusoke", "Kishore", "Kyewuta", "Kyobe", "Lutaaya", "Mangela", "Masaba", "Miyagi", "Mubiru", "Muhumza", "Mukasa", "Munir", "Murungi", "Musoke", "Mutyagaba", "Nakrani", "Nsubuga", "Obuya", "Ochan", "Okia", "Olipa", "Olwenyi", "Ondeko", "Otim", "Otiti", "Otwani", "Patel", "Ramjani", "Saleh", "Sebanja", "Sebulime", "Seiga", "Selowa", "Sematimba", "Senyondo", "Ssemanda", "Ssesazi", "Tabby", "Thawithemwira", "Wabwire", "Waiswa", "Ziraba"]
  },
  "United Arab Emirates": {
    first: ["Aayan", "Abdul", "Adil", "Adnan", "Ahmed", "Akif", "Ali", "Alishan", "Amir", "Amjad", "Ansh", "Arfan", "Aryan", "Aryansh", "Ashfaq", "Asif", "Asim", "Atif", "Awais", "Bakthiyar", "Basil", "Chirag", "Chundangapoyil", "Darius", "Dhruv", "Ethan", "Fahad", "Faizan", "Farhan", "Fayyaz", "Ghulam", "Imran", "Jash", "Junaid", "Kamran", "Kashif", "Khalid", "Khurram", "Laxman", "Manjula", "Mayank", "Mohammad", "Mohammed", "Muhammad", "Muhammed", "Naeemuddin", "Nasir", "Nilansh", "Omid", "Palaniapan", "Qadar", "Qadeer", "Qasim", "Rahul", "Rameez", "Raziq", "Rohan", "Sabir", "Salman", "Samal", "Sanchit", "Saqib", "Saqlain", "Shadeep", "Shaiman", "Sharif", "Simranjeet", "Sultan", "Swapnil", "Syed", "Tahir", "Tanish", "Umair", "Usman", "Vikrant", "Vishnu", "Vriitya", "Waheed", "Waseem", "Zaheer", "Zahoor", "Zawar", "Zuhaib"],
    last: ["Afzal Khan", "Ahmed", "Alam", "Ali", "Ali Khan", "Anwar", "Aravind", "Asadullah", "Asif", "Aslam", "Ayaz", "Azam", "Aziz", "Boota", "Chopra", "D'Silva", "D'Souza", "Daud", "Faraazuddin", "Farid", "Faris", "Farooq", "Giyanani", "Gul", "Guruge", "Haider", "Hameed", "Hayat", "Iqbal", "Javed", "Jawadullah", "Kaleem", "Kang", "Keswani", "Khan", "Khurshid", "Kumar", "Lakra", "Maqsood", "Meiyappan", "Mufti", "Muhammad", "Mushtaq", "Mustafa", "Naseer", "Naveed", "Nawaz", "Palekar", "Parashar", "Patil", "Qasim", "Raja", "Raza", "Rehman", "Riyal", "Rizwan", "Shabber", "Shafi Rahman", "Shafiq", "Shah", "Shahzad", "Shakoor", "Shanil", "Sharafu", "Sharma", "Shazad", "Shetty", "Siddique", "Silva", "Sreekumar", "Sukumaran", "Sultan", "Suri", "Tandon", "Tariq", "Tauqir", "Udawaththa", "Usman", "Zubair"]
  },
  "United States of America": {
    first: ["Aaron", "Adam", "Alex", "Andrew", "Austin", "Brandon", "Brian", "Caleb", "Cameron", "Carlos", "Charles", "Chris", "Corey", "Daniel", "David", "Derek", "Dylan", "Elijah", "Eric", "Ethan", "Gabriel", "George", "Grant", "Hayden", "Hunter", "Ian", "Jack", "Jacob", "James", "Jason", "Jayden", "John", "Jordan", "Joshua", "Justin", "Keith", "Kevin", "Kyle", "Liam", "Logan", "Luke", "Marcus", "Mason", "Matthew", "Michael", "Nathan", "Nicholas", "Noah", "Oliver", "Owen", "Patrick", "Paul", "Peter", "Philip", "Robert", "Ryan", "Samuel", "Scott", "Sean", "Shane", "Stephen", "Steven", "Thomas", "Timothy", "Travis", "Tyler", "Wesley", "William", "Xavier", "Zachary"],
    last: ["Adams", "Allen", "Anderson", "Baker", "Barnes", "Bell", "Bennett", "Brooks", "Brown", "Butler", "Campbell", "Carter", "Clark", "Collins", "Cook", "Cooper", "Cruz", "Davis", "Edwards", "Evans", "Fisher", "Foster", "Garcia", "Gonzalez", "Green", "Griffin", "Hall", "Harris", "Harrison", "Henderson", "Hernandez", "Hill", "Howard", "Hughes", "Jackson", "James", "Jenkins", "Johnson", "Jones", "Kelly", "King", "Lee", "Lewis", "Lopez", "Martin", "Martinez", "Miller", "Mitchell", "Moore", "Morgan", "Morris", "Murphy", "Nelson", "Parker", "Patterson", "Perez", "Peterson", "Phillips", "Powell", "Price", "Reed", "Richardson", "Rivera", "Robinson", "Rodriguez", "Rogers", "Ross", "Russell", "Sanders", "Scott", "Smith", "Stewart", "Sullivan", "Taylor", "Thomas", "Thompson", "Turner", "Walker", "Ward", "Washington", "Watson", "White", "Williams", "Wilson", "Wood", "Wright", "Young"]
  },
  "Vanuatu": {
    first: ["Andrew", "Apolinaire", "Callum", "Clement", "Darren", "Gilmour", "Jamal", "Jarryd", "Jelany", "Jonathon", "Joshua", "Junior", "Nalin", "Obed", "Patrick", "Rival", "Ronald", "Simpson", "Trevor", "Wesley", "Williamsing", "Wolford", "Womejo", "Zechariah"],
    last: ["Allan", "Blake", "Chilia", "Dunn", "Kaltapau", "Kaltongga", "Kalworai", "Langa", "Mansale", "Matautaava", "Nalisa", "Nipiko", "Obed", "Rasu", "Samson", "Shem", "Stephen", "Tari", "Tommy", "Vira", "Viraliliu", "Wotu", "Yosef"]
  },
  "West Indies": {
    first: ["Adrian", "Akeal", "Alick", "Alzarri", "Andre", "Anthony", "Ashley", "Austin", "Brandon", "Brenton", "Carlos", "Carlton", "Chadwick", "Chris", "Christopher", "Dale", "Danza", "Daren", "Darren", "David", "Deighton", "Denesh", "Derwin", "Devendra", "Devon", "Dominic", "Dwayne", "Evin", "Fabian", "Fidel", "Floyd", "Garey", "Gavin", "Gudakesh", "Hayden", "Ian", "Jason", "Jayden", "Jerome", "John", "Johnson", "Jonathan", "Justin", "Keemo", "Kemar", "Kesrick", "Kevin", "Khary", "Kieran", "Kieron", "Krishmar", "Kyle", "Lendl", "Lionel", "Marlon", "Matthew", "Miles", "Narsingh", "Nicholas", "Nikita", "Nkruma", "Obed", "Odean", "Oshane", "Ramnaresh", "Ravi", "Rawl", "Rayad", "Raymon", "Romario", "Roston", "Rovman", "Runako", "Samuel", "Shai", "Shamar", "Shannon", "Sharmarh", "Shawn", "Sheldon", "Sherfane", "Shimron", "Shivnarine", "Sulieman", "Sunil", "Terrance", "Tino", "Travis", "Veerasammy", "Wavell", "William", "Xavier", "Yannic"],
    last: ["Allen", "Athanaze", "Badree", "Baker", "Barath", "Barnwell", "Bascombe", "Baugh", "Benn", "Bernard", "Best", "Bishoo", "Bonner", "Bradshaw", "Brathwaite", "Bravo", "Brooks", "Butler", "Campbell", "Cariah", "Carter", "Chanderpaul", "Charles", "Chase", "Christian", "Cotterrell", "Deonarine", "Dowlin", "Drakes", "Edwards", "Emrit", "Findlay", "Fletcher", "Forde", "Gabriel", "Ganga", "Gayle", "Greaves", "Hetmyer", "Hinds", "Holder", "Hope", "Hosein", "Hyatt", "Joseph", "King", "Lewis", "Marshall", "Martin", "Mathurin", "Mayers", "McCarthy", "McCoy", "Miller", "Mohammed", "Morton", "Motie", "Narine", "Nurse", "Parchment", "Paul", "Perkins", "Permaul", "Pierre", "Pollard", "Pooran", "Powell", "Ramdin", "Rampaul", "Reifer", "Richards", "Roach", "Russell", "Rutherford", "Sammy", "Samuels", "Santokie", "Sarwan", "Seales", "Shepherd", "Simmons", "Sinclair", "Smith", "Springer", "Taylor", "Thomas", "Tonge", "Walsh", "Walton", "Williams"]
  },
  "Zimbabwe": {
    first: ["Ainsley", "Andy", "Anthony", "Blessing", "Bothwell", "Brad", "Brandon", "Brendan", "Brian", "Carl", "Cephas", "Chamu", "Charles", "Charlton", "Chris", "Clive", "Craig", "Daniel", "Dion", "Donald", "Ed", "Elton", "Faraz", "Forster", "Gary", "George", "Graeme", "Greg", "Hamilton", "Innocent", "Jeremy", "John", "Johnathan", "Joylord", "Keegan", "Keith", "Kevin", "Kudakwashe", "Kudzai", "Kyle", "Luke", "Malcolm", "Milton", "Mluleki", "Nathan", "Natsai", "Neville", "Nick", "Nyasha", "Peter", "Prosper", "Ray", "Regis", "Richard", "Richmond", "Rugare", "Ryan", "Sean", "Shingi", "Sikandar", "Solomon", "Steven", "Stuart", "Tadiwanashe", "Tafadzwa", "Tanaka", "Tarisai", "Tashinga", "Tatenda", "Taurai", "Tawanda", "Tendai", "Timycen", "Tinashe", "Tino", "Tinotenda", "Tony", "Trevor", "Victor", "Vusi", "Wellington", "Wesley", "William"],
    last: ["Akram", "Ballance", "Banda", "Bennett", "Blignaut", "Brent", "Burl", "Campbell", "Chakabva", "Chapungu", "Chari", "Chatara", "Chibhabha", "Chigumbura", "Chisoro", "Chivanga", "Coventry", "Cremer", "Dabengwa", "Ervine", "Evans", "Gumbie", "Gwandu"]
  },
};

export default COUNTRY_NAMES;
