export const CAREER_MODES = {
  CLUB: 'CLUB',
  INTERNATIONAL: 'INTERNATIONAL'
};

export const INTERNATIONAL_COUNTRIES = [
  'Afghanistan',
  'Argentina',
  'Australia',
  'Austria',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Belize',
  'Bermuda',
  'Bhutan',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Chile',
  'China',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'England',
  'Estonia',
  'Fiji',
  'Finland',
  'France',
  'Gambia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Hong Kong',
  'Hungary',
  'India',
  'Indonesia',
  'Iran',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Kenya',
  'Kuwait',
  'Lesotho',
  'Luxembourg',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Mongolia',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Peru',
  'Philippines',
  'Portugal',
  'Qatar',
  'Romania',
  'Rwanda',
  'Samoa',
  'Saudi Arabia',
  'Scotland',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Tanzania',
  'Thailand',
  'Turkey',
  'Uganda',
  'United Arab Emirates',
  'United States of America',
  'Vanuatu',
  'West Indies',
  'Zimbabwe'
];

export function normalizeCareerMode(value) {
  const normalized = String(value || '').trim().toUpperCase();
  return normalized === CAREER_MODES.INTERNATIONAL ? CAREER_MODES.INTERNATIONAL : CAREER_MODES.CLUB;
}

export function isInternationalMode(value) {
  return normalizeCareerMode(value) === CAREER_MODES.INTERNATIONAL;
}

